const COUNTRIES_GLOBAL = [
  "中国 (CHN)", "日本 (JPN)", "法国 (FRA)", "德国 (GER)", "瑞典 (SWE)", "韩国 (KOR)", 
  "中国台北 (TPE)", "巴西 (BRA)", "尼日利亚 (NGR)", "英格兰 (ENG)", "葡萄牙 (POR)", 
  "埃及 (EGY)", "斯洛文尼亚 (SLO)", "中国香港 (HKG)", "印度 (IND)", "美国 (USA)", 
  "丹麦 (DEN)", "新加坡 (SGP)", "澳大利亚 (AUS)", "奥地利 (AUT)", "罗马尼亚 (ROU)",
  "波兰 (POL)", "捷克 (CZE)", "斯洛伐克 (SVK)", "克罗地亚 (CRO)", "塞尔维亚 (SRB)",
  "意大利 (ITA)", "西班牙 (ESP)", "比利时 (BEL)", "希腊 (GRE)", "匈牙利 (HUN)",
  "加拿大 (CAN)", "智利 (CHI)", "阿根廷 (ARG)", "波多黎各 (PUR)", "古巴 (CUB)",
  "哈萨克斯坦 (KAZ)", "泰国 (THA)", "马来西亚 (MAS)", "伊朗 (IRI)", "沙特阿拉伯 (KSA)",
  "土耳其 (TUR)", "阿尔及利亚 (ALG)", "突尼斯 (TUN)", "塞内加尔 (SEN)", "新西兰 (NZL)",
  "乌克兰 (UKR)", "保加利亚 (BUL)", "卡塔尔 (QAT)", "厄瓜多尔 (ECU)", "墨西哥 (MEX)",
  "巴拉圭 (PAR)", "摩尔多瓦 (MDA)", "科索沃 (KOS)", "黑山 (MNE)"
];

const BASE_REAL_STARS_CN = [
  { name: "王楚钦", country: "中国 (CHN)", points: 8200, age: 26, style: "横板两面暴力弧圈", basePow: 92, injury: "健康", prevRank: 1 },
  { name: "林诗栋", country: "中国 (CHN)", points: 7650, age: 21, style: "横板反手快撕大师", basePow: 90, injury: "健康", prevRank: 2 },
  { name: "樊振东", country: "中国 (CHN)", points: 6900, age: 29, style: "横板终极重炮对拉", basePow: 93, injury: "健康", prevRank: 3 },
  { name: "雨果·卡尔德拉诺", country: "巴西 (BRA)", points: 5800, age: 30, style: "中远台大力量进攻", basePow: 88, injury: "健康", prevRank: 4 },
  { name: "费利克斯·勒布伦", country: "法国 (FRA)", points: 5400, age: 20, style: "直拍横打极速突击", basePow: 87, injury: "健康", prevRank: 5 },
  { name: "张本智和", country: "日本 (JPN)", points: 5150, age: 23, style: "近台超强速度反撕", basePow: 86, injury: "健康", prevRank: 6 },
  { name: "特鲁斯·莫雷加德", country: "瑞典 (SWE)", points: 4800, age: 24, style: "六边形异形拍灵动变线", basePow: 85, injury: "健康", prevRank: 7 },
  { name: "梁靖崑", country: "中国 (CHN)", points: 4500, age: 30, style: "横板重炮大路相持", basePow: 86, injury: "健康", prevRank: 8 },
  { name: "林昀儒", country: "中国台北 (TPE)", points: 4100, age: 25, style: "反手黄金拧拉大师", basePow: 84, injury: "健康", prevRank: 9 },
  { name: "帕特里克·弗朗西斯卡", country: "德国 (GER)", points: 3400, age: 34, style: "欧洲大力量弧圈", basePow: 82, injury: "健康", prevRank: 10 },
  { name: "马龙", country: "中国 (CHN)", points: 3350, age: 38, style: "六边形终极掌控", basePow: 91, injury: "膝盖劳损", prevRank: 11 },
  { name: "安东·卡尔伯格", country: "瑞典 (SWE)", points: 2900, age: 29, style: "近中台快攻结合弧圈", basePow: 81, injury: "健康", prevRank: 12 },
  { name: "邱党", country: "德国 (GER)", points: 2850, age: 30, style: "传统直拍正胶与横打", basePow: 80, injury: "健康", prevRank: 13 },
  { name: "达科·约奇克", country: "斯洛文尼亚 (SLO)", points: 2700, age: 28, style: "反手暴冲弹击型", basePow: 80, injury: "健康", prevRank: 14 },
  { name: "夸德里·阿鲁纳", country: "尼日利亚 (NGR)", points: 2450, age: 38, style: "正手超强重炮手", basePow: 79, injury: "健康", prevRank: 15 },
  { name: "艾利克斯·勒布伦", country: "法国 (FRA)", points: 2300, age: 23, style: "神经刀暴力发抢", basePow: 79, injury: "健康", prevRank: 16 },
  { name: "蒂姆·波尔", country: "德国 (GER)", points: 1950, age: 45, style: "旋转弧圈艺术大师", basePow: 82, injury: "老伤反复", prevRank: 17 },
  { name: "户上隼辅", country: "日本 (JPN)", points: 1900, age: 25, style: "两面快弧进攻型", basePow: 78, injury: "健康", prevRank: 18 },
  { name: "松岛辉空", country: "日本 (JPN)", points: 1850, age: 19, style: "左手两面反胶快攻", basePow: 77, injury: "健康", prevRank: 19 },
  { name: "高承睿", country: "中国台北 (TPE)", points: 1750, age: 21, style: "近台快攻突击型", basePow: 76, injury: "健康", prevRank: 20 },
  { name: "奥恰洛夫", country: "德国 (GER)", points: 1700, age: 38, style: "潜艇发球暴力反手", basePow: 80, injury: "背部劳损", prevRank: 21 },
  { name: "庄智渊", country: "中国台北 (TPE)", points: 1600, age: 45, style: "近台快攻老将", basePow: 76, injury: "健康", prevRank: 22 },
  { name: "西蒙·高茨", country: "法国 (FRA)", points: 1550, age: 32, style: "魔术师手感放高球", basePow: 77, injury: "健康", prevRank: 23 },
  { name: "卡纳克·贾哈", country: "美国 (USA)", points: 1450, age: 26, style: "稳健防守反击型", basePow: 75, injury: "健康", prevRank: 24 },
  { name: "马蒂亚斯·法尔克", country: "瑞典 (SWE)", points: 1400, age: 35, style: "正手正胶异质快攻", basePow: 76, injury: "健康", prevRank: 25 },
  { name: "贝内迪克特·杜达", country: "德国 (GER)", points: 1350, age: 32, style: "左手中台重炮对拉", basePow: 76, injury: "健康", prevRank: 26 },
  { name: "黄镇廷", country: "中国香港 (HKG)", points: 1300, age: 35, style: "传统直拍横打快变", basePow: 75, injury: "健康", prevRank: 27 },
  { name: "李尚洙", country: "韩国 (KOR)", points: 1250, age: 36, style: "近台拼命三郎狂攻", basePow: 75, injury: "健康", prevRank: 28 },
  { name: "安宰贤", country: "韩国 (KOR)", points: 1200, age: 27, style: "两面弧圈相持型", basePow: 74, injury: "健康", prevRank: 29 },
  { name: "赵大成", country: "韩国 (KOR)", points: 1150, age: 24, style: "左手快弧结合变线", basePow: 74, injury: "健康", prevRank: 30 },
  { name: "张禹珍", country: "韩国 (KOR)", points: 1100, age: 31, style: "正手狂奔大范围暴冲", basePow: 75, injury: "健康", prevRank: 31 },
  { name: "林钟勋", country: "韩国 (KOR)", points: 1080, age: 29, style: "左手两面拧拉突击", basePow: 75, injury: "健康", prevRank: 32 },
  { name: "篠塚大登", country: "日本 (JPN)", points: 1050, age: 22, style: "左手灵巧落点相持", basePow: 73, injury: "健康", prevRank: 33 },
  { name: "宇田幸矢", country: "日本 (JPN)", points: 1020, age: 25, style: "左手近台前冲弧圈", basePow: 74, injury: "健康", prevRank: 34 },
  { name: "田中佑汰", country: "日本 (JPN)", points: 980, age: 26, style: "稳健两面均衡防守", basePow: 72, injury: "健康", prevRank: 35 },
  { name: "吉村真晴", country: "日本 (JPN)", points: 960, age: 33, style: "勾手发球正手反拉", basePow: 73, injury: "健康", prevRank: 36 },
  { name: "向鹏", country: "中国 (CHN)", points: 950, age: 23, style: "正手大角度反拉爆冲", basePow: 76, injury: "健康", prevRank: 37 },
  { name: "周启豪", country: "中国 (CHN)", points: 920, age: 29, style: "神经刀暴力弧圈流", basePow: 76, injury: "健康", prevRank: 38 },
  { name: "徐瑛彬", country: "中国 (CHN)", points: 890, age: 25, style: "近台快弧相持型", basePow: 73, injury: "健康", prevRank: 39 },
  { name: "袁励岑", country: "中国 (CHN)", points: 870, age: 26, style: "左手两面快撕变线", basePow: 73, injury: "健康", prevRank: 40 },
  { name: "陈垣宇", country: "中国 (CHN)", points: 850, age: 21, style: "两面弧圈新生代", basePow: 72, injury: "健康", prevRank: 41 },
  { name: "黄友政", country: "中国 (CHN)", points: 830, age: 21, style: "反手速度快撕型", basePow: 71, injury: "健康", prevRank: 42 },
  { name: "温瑞博", country: "中国 (CHN)", points: 800, age: 19, style: "反手大力量暴冲", basePow: 71, injury: "健康", prevRank: 43 },
  { name: "薛飞", country: "中国 (CHN)", points: 780, age: 27, style: "直拍横打传统继承", basePow: 72, injury: "健康", prevRank: 44 },
  { name: "利亚姆·皮切福德", country: "英格兰 (ENG)", points: 760, age: 33, style: "反手超音速反撕", basePow: 75, injury: "健康", prevRank: 45 },
  { name: "马科斯·弗雷塔斯", country: "葡萄牙 (POR)", points: 740, age: 38, style: "左手稳健相持大师", basePow: 74, injury: "健康", prevRank: 46 },
  { name: "约纳坦·格罗特", country: "丹麦 (DEN)", points: 720, age: 34, style: "左手大范围相持", basePow: 73, injury: "健康", prevRank: 47 },
  { name: "阿尔瓦罗·罗伯勒斯", country: "西班牙 (ESP)", points: 700, age: 35, style: "左手弧圈旋转型", basePow: 72, injury: "健康", prevRank: 48 },
  { name: "奥马尔·阿萨尔", country: "埃及 (EGY)", points: 680, age: 35, style: "欧洲型高大防守相持", basePow: 74, injury: "健康", prevRank: 49 },
  { name: "沙拉斯·卡玛尔", country: "印度 (IND)", points: 650, age: 44, style: "高大力量弧圈老将", basePow: 73, injury: "健康", prevRank: 50 }
];

const REAL_PLAYERS_EXTENDED_DATABASE = [
  // --- 中国 (CHN) ---
  { name: "徐晨皓", country: "中国 (CHN)", age: 31, style: "横板大力量相持" },
  { name: "孙闻", country: "中国 (CHN)", age: 29, style: "狂暴正手进攻型" },
  { name: "刘丁硕", country: "中国 (CHN)", age: 28, style: "稳健两面弧圈" },
  { name: "于子洋", country: "中国 (CHN)", age: 28, style: "左手快弧相持" },
  { name: "曹巍", country: "中国 (CHN)", age: 27, style: "左手双打大师" },
  { name: "牛冠凯", country: "中国 (CHN)", age: 25, style: "防守反击型" },
  { name: "全开源", country: "中国 (CHN)", age: 25, style: "两面弧圈相持" },
  { name: "赛林威", country: "中国 (CHN)", age: 26, style: "正手爆冲型" },
  { name: "梁俨苧", country: "中国 (CHN)", age: 25, style: "两面均衡快弧" },
  { name: "曾蓓勋", country: "中国 (CHN)", age: 23, style: "反手极速快撕" },
  { name: "徐海东", country: "中国 (CHN)", age: 26, style: "直拍正胶横打" },
  { name: "严升", country: "中国 (CHN)", age: 27, style: "传统直拍左推右攻" },
  { name: "胡东申", country: "中国 (CHN)", age: 24, style: "削球防守反击" },
  { name: "陶育畅", country: "中国 (CHN)", age: 22, style: "快攻结合弧圈" },
  { name: "祝佳祺", country: "中国 (CHN)", age: 20, style: "灵动快变进攻" },
  { name: "李天阳", country: "中国 (CHN)", age: 22, style: "两面反胶快攻" },
  { name: "高杨", country: "中国 (CHN)", age: 24, style: "左手相持进攻" },
  { name: "王廷宇", country: "中国 (CHN)", age: 21, style: "近台快攻型" },
  { name: "朱霖峰", country: "中国 (CHN)", age: 30, style: "左手两面反胶" },
  { name: "朱毅", country: "中国 (CHN)", age: 32, style: "民间直拍高手" },
  { name: "郑培锋", country: "中国 (CHN)", age: 30, style: "传统直拍快攻" },
  { name: "张超", country: "中国 (CHN)", age: 41, style: "正手暴冲大汉" },
  { name: "郝帅", country: "中国 (CHN)", age: 43, style: "手感落点大师" },
  { name: "邱贻可", country: "中国 (CHN)", age: 41, style: "神经刀全台暴冲" },
  { name: "陈玘", country: "中国 (CHN)", age: 42, style: "杀神左手狂飙" },
  { name: "侯英超", country: "中国 (CHN)", age: 46, style: "正手正胶反手生胶削球" },
  { name: "王励勤", country: "中国 (CHN)", age: 48, style: "正手天下第一大力相持" },
  { name: "马琳", country: "中国 (CHN)", age: 46, style: "直拍魔术师控制大师" },
  { name: "王皓", country: "中国 (CHN)", age: 43, style: "直拍横打终极形态" },
  { name: "刘国正", country: "中国 (CHN)", age: 46, style: "抗压大心脏相持" },
  { name: "孔令辉", country: "中国 (CHN)", age: 51, style: "乒乓王子相持稳健" },
  { name: "刘国梁", country: "中国 (CHN)", age: 50, style: "直拍发抢变化大师" },
  { name: "丁松", country: "中国 (CHN)", age: 55, style: "削中反攻魔术师" },
  { name: "王涛", country: "中国 (CHN)", age: 59, style: "反手生胶快弹大师" },
  { name: "吕林", country: "中国 (CHN)", age: 57, style: "双打黄金搭档" },
  { name: "阎森", country: "中国 (CHN)", age: 51, style: "左手双打鬼才" },
  { name: "秦志戬", country: "中国 (CHN)", age: 50, style: "左手直拍落点型" },
  { name: "江嘉良", country: "中国 (CHN)", age: 62, style: "传统直拍快攻" },
  { name: "谢赛克", country: "中国 (CHN)", age: 64, style: "直拍生胶进攻" },
  { name: "郭跃华", country: "中国 (CHN)", age: 70, style: "全台单面拉大师" },
  { name: "蔡振华", country: "中国 (CHN)", age: 65, style: "异质倒板大师" },
  { name: "施之皓", country: "中国 (CHN)", age: 66, style: "直拍快攻结合弧圈" },
  { name: "黄亮", country: "中国 (CHN)", age: 68, style: "稳健防守反击" },
  { name: "陆元盛", country: "中国 (CHN)", age: 72, style: "直拍削球防守" },
  { name: "刁明智", country: "中国 (CHN)", age: 65, style: "左手两面弧圈" },
  { name: "梁戈亮", country: "中国 (CHN)", age: 76, style: "削球进攻大师" },
  { name: "李振恃", country: "中国 (CHN)", age: 77, style: "直拍近台快攻" },
  { name: "许绍发", country: "中国 (CHN)", age: 79, style: "快带快拉大师" },
  { name: "郗恩庭", country: "中国 (CHN)", age: 78, style: "推挡与弧圈结合" },
  { name: "庄则栋", country: "中国 (CHN)", age: 80, style: "三连冠近台两面快攻" },
  { name: "李富荣", country: "中国 (CHN)", age: 84, style: "轰炸机正手快攻" },
  { name: "徐寅生", country: "中国 (CHN)", age: 88, style: "十二大板扣杀大师" },
  { name: "张燮林", country: "中国 (CHN)", age: 86, style: "魔术长胶削球" },
  { name: "容国团", country: "中国 (CHN)", age: 85, style: "中国首位世界冠军" },
  { name: "周兰荪", country: "中国 (CHN)", age: 84, style: "重板大力量扣杀" },
  { name: "王家声", country: "中国 (CHN)", age: 83, style: "直拍正胶快攻" },
  { name: "余长春", country: "中国 (CHN)", age: 82, style: "两面反胶快弧" },
  { name: "苏国熙", country: "中国 (CHN)", age: 80, style: "快速相持进攻" },
  { name: "胡道本", country: "中国 (CHN)", age: 81, style: "直拍左推右攻" },
  { name: "冯喆", country: "中国 (CHN)", age: 38, style: "近台快弧结合" },
  { name: "单明杰", country: "中国 (CHN)", age: 43, style: "两面弧圈突击" },
  { name: "雷振华", country: "中国 (CHN)", age: 41, style: "正手爆冲大力量" },
  { name: "李平", country: "中国 (CHN)", age: 40, style: "稳健两面弧圈" },
  { name: "徐克", country: "中国 (CHN)", age: 35, style: "近台快撕变线" },
  { name: "刘吉康", country: "中国 (CHN)", age: 34, style: "正手中台中远台拉冲" },
  { name: "赖佳新", country: "中国 (CHN)", age: 31, style: "左手快弧相持" },
  { name: "房胤池", country: "中国 (CHN)", age: 30, style: "横板大力量进攻" },
  { name: "孔令轩", country: "中国 (CHN)", age: 30, style: "左手快速拉冲" },
  { name: "程靖淇", country: "中国 (CHN)", age: 32, style: "左手灵巧反拉" },
  { name: "宋旭", country: "中国 (CHN)", age: 27, style: "快速相持突击" },
  { name: "李明博", country: "中国 (CHN)", age: 26, style: "两面反胶进攻" },
  { name: "马金宝", country: "中国 (CHN)", age: 25, style: "正手爆冲型" },
  { name: "李泽燕", country: "中国 (CHN)", age: 24, style: "反手快速快撕" },

  // --- 中国香港 (HKG) ---
  { name: "林兆恒", country: "中国香港 (HKG)", age: 29, style: "横板快攻相持" },
  { name: "何钧杰", country: "中国香港 (HKG)", age: 29, style: "左手快弧结合" },
  { name: "陈颢桦", country: "中国香港 (HKG)", age: 21, style: "反手极速突击" },
  { name: "姚钧涛", country: "中国香港 (HKG)", age: 21, style: "中远台反拉" },
  { name: "关文皓", country: "中国香港 (HKG)", age: 28, style: "稳健两面相持" },
  { name: "李汉铭", country: "中国香港 (HKG)", age: 30, style: "反手弹击型" },
  { name: "鲍奕文", country: "中国香港 (HKG)", age: 22, style: "快速相持弧圈" },
  { name: "苏致", country: "中国香港 (HKG)", age: 26, style: "两面反胶快攻" },
  { name: "李静", country: "中国香港 (HKG)", age: 51, style: "直拍双打名宿" },
  { name: "高礼泽", country: "中国香港 (HKG)", age: 50, style: "左手直拍名宿" },
  { name: "唐鹏", country: "中国香港 (HKG)", age: 45, style: "正手重炮快攻" },
  { name: "江天一", country: "中国香港 (HKG)", age: 38, style: "左手两面弧圈" },
  { name: "张钰", country: "中国香港 (HKG)", age: 44, style: "左手生胶名宿" },
  { name: "梁柱恩", country: "中国香港 (HKG)", age: 47, style: "相持控制型" },
  { name: "何振廷", country: "中国香港 (HKG)", age: 23, style: "近台快撕型" },
  { name: "曾梓峻", country: "中国香港 (HKG)", age: 22, style: "反手快弹突击" },
  { name: "李彦衡", country: "中国香港 (HKG)", age: 21, style: "两面弧圈相持" },
  { name: "蔡俊杰", country: "中国香港 (HKG)", age: 24, style: "快速进攻型" },
  { name: "麦景皓", country: "中国香港 (HKG)", age: 28, style: "防守反击型" },
  { name: "关天朗", country: "中国香港 (HKG)", age: 25, style: "近台快弧型" },

  // --- 中国台北 (TPE) ---
  { name: "冯翊新", country: "中国台北 (TPE)", age: 23, style: "两面反胶进攻" },
  { name: "黄彦诚", country: "中国台北 (TPE)", age: 23, style: "近台快撕变线" },
  { name: "廖振珽", country: "中国台北 (TPE)", age: 29, style: "正手爆冲型" },
  { name: "陈建安", country: "中国台北 (TPE)", age: 35, style: "左手两面弧圈" },
  { name: "张佑安", country: "中国台北 (TPE)", age: 20, style: "左手灵巧型" },
  { name: "洪敬恺", country: "中国台北 (TPE)", age: 19, style: "快速相持新秀" },
  { name: "郭冠宏", country: "中国台北 (TPE)", age: 18, style: "反手拧拉天才" },
  { name: "彭王维", country: "中国台北 (TPE)", age: 27, style: "两面弧圈相持" },
  { name: "杨子仪", country: "中国台北 (TPE)", age: 28, style: "防守反击型" },
  { name: "蒋澎龙", country: "中国台北 (TPE)", age: 50, style: "鬼之推挡单面拉" },
  { name: "张雁书", country: "中国台北 (TPE)", age: 47, style: "快攻双打大师" },
  { name: "吴志祺", country: "中国台北 (TPE)", age: 40, style: "左手稳健相持" },
  { name: "江宏杰", country: "中国台北 (TPE)", age: 37, style: "横板快速两面" },
  { name: "孙嘉宏", country: "中国台北 (TPE)", age: 28, style: "反手快撕相持" },
  { name: "黎昕阳", country: "中国台北 (TPE)", age: 24, style: "两面反胶快攻" },
  { name: "王泰崴", country: "中国台北 (TPE)", age: 27, style: "正手暴冲突击" },
  { name: "李佳陞", country: "中国台北 (TPE)", age: 30, style: "中远台对拉" },
  { name: "黄建都", country: "中国台北 (TPE)", age: 29, style: "左手快弧相持" },
  { name: "杨恒韦", country: "中国台北 (TPE)", age: 28, style: "快速突击型" },
  { name: "林彦均", country: "中国台北 (TPE)", age: 22, style: "两面均衡快攻" },

  // --- 日本 (JPN) ---
  { name: "及川瑞基", country: "日本 (JPN)", age: 29, style: "全台稳健防守反击" },
  { name: "吉村和弘", country: "日本 (JPN)", age: 30, style: "两面弧圈重炮" },
  { name: "滨田一辉", country: "日本 (JPN)", age: 23, style: "近台快攻突击" },
  { name: "吉山僚一", country: "日本 (JPN)", age: 22, style: "反手大力量反撕" },
  { name: "吉山和希", country: "日本 (JPN)", age: 19, style: "灵巧速度进攻" },
  { name: "萩原启至", country: "日本 (JPN)", age: 20, style: "左手两面反胶" },
  { name: "木造勇人", country: "日本 (JPN)", age: 27, style: "左手前冲弧圈" },
  { name: "森园政崇", country: "日本 (JPN)", age: 31, style: "左手极限跑位暴冲" },
  { name: "神巧也", country: "日本 (JPN)", age: 33, style: "咆哮正手爆攻" },
  { name: "英田理志", country: "日本 (JPN)", age: 33, style: "现代削中反攻" },
  { name: "町飞鸟", country: "日本 (JPN)", age: 32, style: "两面稳健相持" },
  { name: "谷垣佑真", country: "日本 (JPN)", age: 23, style: "正手进攻型" },
  { name: "松平健太", country: "日本 (JPN)", age: 35, style: "下蹲发球防守魔术师" },
  { name: "水谷隼", country: "日本 (JPN)", age: 37, style: "中远台手感掌控大师" },
  { name: "丹羽孝希", country: "日本 (JPN)", age: 32, style: "佛系侧切神仙球大师" },
  { name: "吉田雅己", country: "日本 (JPN)", age: 32, style: "反手快撕弧圈" },
  { name: "村松雄斗", country: "日本 (JPN)", age: 30, style: "正手暴冲现代削球" },
  { name: "盐野真人", country: "日本 (JPN)", age: 40, style: "古典纯削球大师" },
  { name: "大岛祐哉", country: "日本 (JPN)", age: 32, style: "正手极速步法重炮" },
  { name: "岸川圣也", country: "日本 (JPN)", age: 39, style: "两面反胶控制" },
  { name: "松平贤二", country: "日本 (JPN)", age: 37, style: "正手铁血硬汉" },
  { name: "上田仁", country: "日本 (JPN)", age: 34, style: "稳健两面相持" },
  { name: "笠原弘光", country: "日本 (JPN)", age: 36, style: "近台快弧进攻" },
  { name: "高木和卓", country: "日本 (JPN)", age: 37, style: "反手快速弹击" },
  { name: "有延大梦", country: "日本 (JPN)", age: 31, style: "正手重炮弧圈" },
  { name: "定松祐辅", country: "日本 (JPN)", age: 30, style: "两面反胶相持" },
  { name: "龙崎东寅", country: "日本 (JPN)", age: 28, style: "左手快速拉冲" },
  { name: "冈野俊介", country: "日本 (JPN)", age: 23, style: "近台快攻型" },
  { name: "坂井雄飞", country: "日本 (JPN)", age: 19, style: "两面反胶新秀" },
  { name: "川上流星", country: "日本 (JPN)", age: 17, style: "极速前冲弧圈" },

  // --- 韩国 (KOR) ---
  { name: "吴晙诚", country: "韩国 (KOR)", age: 20, style: "反手极速弹击控球" },
  { name: "赵胜敏", country: "韩国 (KOR)", age: 28, style: "左手凶狠发抢" },
  { name: "朴康贤", country: "韩国 (KOR)", age: 30, style: "左手两面弧圈" },
  { name: "姜东秀", country: "韩国 (KOR)", age: 32, style: "现代削球反攻" },
  { name: "金敏赫", country: "韩国 (KOR)", age: 30, style: "近台快弧结合" },
  { name: "朴奎炫", country: "韩国 (KOR)", age: 21, style: "快速相持新秀" },
  { name: "吉敏锡", country: "韩国 (KOR)", age: 22, style: "两面反胶进攻" },
  { name: "金宇镇", country: "韩国 (KOR)", age: 22, style: "正手中台相持" },
  { name: "郑荣植", country: "韩国 (KOR)", age: 34, style: "反手大路相持大师" },
  { name: "柳承敏", country: "韩国 (KOR)", age: 44, style: "奥运单桧日直暴冲天王" },
  { name: "金泽洙", country: "韩国 (KOR)", age: 56, style: "单桧日直重炮教父" },
  { name: "朱世爀", country: "韩国 (KOR)", age: 46, style: "天下第一削球手" },
  { name: "吴尚垠", country: "韩国 (KOR)", age: 49, style: "绝妙台内控制大师" },
  { name: "刘南奎", country: "韩国 (KOR)", age: 58, style: "首届奥运男单金牌" },
  { name: "金择洙", country: "韩国 (KOR)", age: 55, style: "正手爆冲大师" },
  { name: "丁祥恩", country: "韩国 (KOR)", age: 36, style: "近台拼抢型" },
  { name: "徐贤德", country: "韩国 (KOR)", age: 34, style: "左手快弧相持" },
  { name: "李廷佑", country: "韩国 (KOR)", age: 41, style: "日直单桧快攻" },
  { name: "尹在荣", country: "韩国 (KOR)", age: 43, style: "左手两面弧圈" },
  { name: "赵彦来", country: "韩国 (KOR)", age: 40, style: "中远台拉冲" },
  { name: "张成万", country: "韩国 (KOR)", age: 36, style: "削球防守型" },
  { name: "黄圣德", country: "韩国 (KOR)", age: 33, style: "正手进攻型" },
  { name: "金东贤", country: "韩国 (KOR)", age: 34, style: "稳健两面相持" },
  { name: "白虎均", country: "韩国 (KOR)", age: 22, style: "两面反胶快攻" },
  { name: "李浩锡", country: "韩国 (KOR)", age: 21, style: "近台快撕突击" },

  // --- 德国 (GER) ---
  { name: "理查德·维泽尔", country: "德国 (GER)", age: 28, style: "稳健两面弧圈" },
  { name: "凯·斯通珀", country: "德国 (GER)", age: 23, style: "欧洲新星相持" },
  { name: "塞德里克·迈斯纳", country: "德国 (GER)", age: 26, style: "左手快速拉冲" },
  { name: "斯特芬·孟格尔", country: "德国 (GER)", age: 38, style: "高大力量弧圈" },
  { name: "鲁文·菲鲁斯", country: "德国 (GER)", age: 38, style: "削中反拉反手长胶" },
  { name: "约尔格·罗斯科普夫", country: "德国 (GER)", age: 57, style: "左手重炮名宿" },
  { name: "巴斯蒂安·斯特格", country: "德国 (GER)", age: 45, style: "反手稳健防守" },
  { name: "托尔本·沃斯特", country: "德国 (GER)", age: 35, style: "两面反胶快攻" },
  { name: "基里尔·法捷耶夫", country: "德国 (GER)", age: 24, style: "近台快撕型" },
  { name: "希普勒·格里特", country: "德国 (GER)", age: 26, style: "左手弧圈进攻" },
  { name: "弗朗西斯·鲍姆", country: "德国 (GER)", age: 39, style: "左手两面重炮" },
  { name: "克里斯蒂安·苏斯", country: "德国 (GER)", age: 41, style: "正手爆冲重扣" },
  { name: "费利克斯·韦策尔", country: "德国 (GER)", age: 23, style: "快速相持新秀" },
  { name: "本诺·奥梅", country: "德国 (GER)", age: 22, style: "两面反胶进攻" },
  { name: "托比亚斯·希普勒", country: "德国 (GER)", age: 27, style: "左手快弧相持" },
  { name: "佩特·弗兰兹", country: "德国 (GER)", age: 55, style: "稳健两面弧圈" },
  { name: "尼尔斯·霍迈尔", country: "德国 (GER)", age: 28, style: "正手突击进攻" },
  { name: "丹尼斯·克莱因", country: "德国 (GER)", age: 29, style: "近台快攻突击" },
  { name: "马蒂亚斯·布鲁姆", country: "德国 (GER)", age: 28, style: "中远台对拉" },
  { name: "弗洛里安·布鲁姆", country: "德国 (GER)", age: 25, style: "两面反胶快攻" },

  // --- 法国 (FRA) ---
  { name: "卡米尔·诺德雷斯特", country: "法国 (FRA)", age: 24, style: "反手快速相持" },
  { name: "朱尔斯·罗兰", country: "法国 (FRA)", age: 26, style: "近台快速攻防" },
  { name: "利利安·巴尔代", country: "法国 (FRA)", age: 23, style: "左手两面反胶" },
  { name: "弗洛里安·布拉索", country: "法国 (FRA)", age: 23, style: "快速相持突击" },
  { name: "埃马纽埃尔·勒贝松", country: "法国 (FRA)", age: 38, style: "左手超级重炮" },
  { name: "让·菲利普·盖亭", country: "法国 (FRA)", age: 58, style: "法国狂热左手重炮" },
  { name: "达米安·埃洛瓦", country: "法国 (FRA)", age: 57, style: "跳跃挑打魔术师" },
  { name: "克里斯托弗·勒古", country: "法国 (FRA)", age: 53, style: "横板两面弧圈" },
  { name: "安德里亚·朗比埃", country: "法国 (FRA)", age: 30, style: "反手暴力反撕" },
  { name: "恩佐·安格勒斯", country: "法国 (FRA)", age: 31, style: "稳健防守反击" },
  { name: "罗曼·鲁伊斯", country: "法国 (FRA)", age: 29, style: "左手快速拉冲" },
  { name: "乔·塞弗里德", country: "法国 (FRA)", age: 28, style: "正手爆冲型" },
  { name: "巴斯蒂安·雷米", country: "法国 (FRA)", age: 27, style: "两面弧圈相持" },
  { name: "文森特·皮卡尔", country: "法国 (FRA)", age: 25, style: "近台快撕型" },
  { name: "蒂博·波雷", country: "法国 (FRA)", age: 22, style: "快速进攻新秀" },
  { name: "弗拉维安·科东", country: "法国 (FRA)", age: 18, style: "两面反胶快攻" },
  { name: "亚历克西斯·库拉奇基", country: "法国 (FRA)", age: 21, style: "反手大力量反撕" },
  { name: "内森·兰比尔", country: "法国 (FRA)", age: 20, style: "灵巧速度攻防" },
  { name: "塞利安·贝斯尼尔", country: "法国 (FRA)", age: 21, style: "左手快弧相持" },
  { name: "莱奥·德·诺德雷斯特", country: "法国 (FRA)", age: 26, style: "稳健两面拉冲" },

  // --- 瑞典 (SWE) ---
  { name: "瓦尔德内尔", country: "瑞典 (SWE)", age: 61, style: "乒坛常青树六边形游击队长" },
  { name: "约尔根·佩尔森", country: "瑞典 (SWE)", age: 60, style: "世界第一反手快撕" },
  { name: "彼得·卡尔松", country: "瑞典 (SWE)", age: 57, style: "相持跑位大师" },
  { name: "埃里克·林德", country: "瑞典 (SWE)", age: 62, style: "左手两面弧圈" },
  { name: "克里斯蒂安·卡尔松", country: "瑞典 (SWE)", age: 35, style: "左手大力量重炮" },
  { name: "乔恩·佩尔森", country: "瑞典 (SWE)", age: 40, style: "正手爆冲快弧" },
  { name: "维利亚姆·伯格伦德", country: "瑞典 (SWE)", age: 24, style: "两面反胶快攻" },
  { name: "马丁·弗里斯", country: "瑞典 (SWE)", age: 22, style: "左手近台快撕" },
  { name: "伊萨克·阿尔弗雷德松", country: "瑞典 (SWE)", age: 20, style: "快速相持新秀" },
  { name: "佩尔·格雷尔", country: "瑞典 (SWE)", age: 44, style: "左手超级旋转发球" },
  { name: "延斯·伦奎斯特", country: "瑞典 (SWE)", age: 47, style: "大力量弧圈对拉" },
  { name: "托马斯·冯·舍勒", country: "瑞典 (SWE)", age: 57, style: "世乒赛双打冠军" },
  { name: "乌尔夫·卡尔松", country: "瑞典 (SWE)", age: 65, style: "稳健防守反击" },
  { name: "米凯尔·阿佩尔格伦", country: "瑞典 (SWE)", age: 64, style: "左手四届欧锦赛冠军" },
  { name: "西蒙·阿尔维德松", country: "瑞典 (SWE)", age: 31, style: "两面弧圈相持" },
  { name: "汉普斯·索德隆德", country: "瑞典 (SWE)", age: 33, style: "近台快攻突击" },
  { name: "维克多·布罗德", country: "瑞典 (SWE)", age: 26, style: "左手快速进攻" },
  { name: "查理·维德隆德", country: "瑞典 (SWE)", age: 21, style: "快速变线型" },
  { name: "埃利亚斯·舍格伦", country: "瑞典 (SWE)", age: 19, style: "反手暴力反撕" },
  { name: "马茨·卡尔松", country: "瑞典 (SWE)", age: 32, style: "稳健攻防结合" },

  // --- 欧洲各协会知名真实选手 ---
  { name: "保罗·金克霍尔", country: "英格兰 (ENG)", age: 36, style: "正手暴力前冲" },
  { name: "塞缪尔·沃克", country: "英格兰 (ENG)", age: 31, style: "稳健相持型" },
  { name: "汤姆·贾维斯", country: "英格兰 (ENG)", age: 27, style: "反手快速拉冲" },
  { name: "大卫·麦克比斯", country: "英格兰 (ENG)", age: 28, style: "近台快攻突击" },
  { name: "丹尼尔·哈贝松", country: "奥地利 (AUT)", age: 40, style: "全台跑位弧圈" },
  { name: "罗伯特·加尔多斯", country: "奥地利 (AUT)", age: 47, style: "反手大力量撕扯" },
  { name: "施拉格", country: "奥地利 (AUT)", age: 54, style: "世乒赛单打冠军发球大师" },
  { name: "陈卫星", country: "奥地利 (AUT)", age: 54, style: "正手暴冲削球老将" },
  { name: "安德雷斯·勒文科", country: "奥地利 (AUT)", age: 28, style: "左手两面弧圈" },
  { name: "马切伊·科洛齐耶奇克", country: "奥地利 (AUT)", age: 25, style: "近台快速攻防" },
  { name: "蒂亚戈·阿波罗尼亚", country: "葡萄牙 (POR)", age: 40, style: "正反手均衡相持" },
  { name: "若昂·格拉尔多", country: "葡萄牙 (POR)", age: 31, style: "左手快速进攻" },
  { name: "若昂·蒙泰罗", country: "葡萄牙 (POR)", age: 43, style: "左手双打高手" },
  { name: "迪奥戈·卡瓦略", country: "葡萄牙 (POR)", age: 33, style: "两面反胶快攻" },
  { name: "帕纳吉奥蒂斯·吉奥尼斯", country: "希腊 (GRE)", age: 46, style: "正手重炮削球铁闸" },
  { name: "卡里尼科斯·格林卡", country: "希腊 (GRE)", age: 54, style: "世界最狂暴力反手" },
  { name: "扬尼斯·斯格罗普洛斯", country: "希腊 (GRE)", age: 26, style: "两面弧圈相持" },
  { name: "康斯坦蒂诺斯·安杰拉基斯", country: "希腊 (GRE)", age: 29, style: "现代削中反攻" },
  { name: "奥维杜·约内斯库", country: "罗马尼亚 (ROU)", age: 37, style: "两面反胶快攻" },
  { name: "爱德华·约内斯库", country: "罗马尼亚 (ROU)", age: 22, style: "近台速度反撕" },
  { name: "达里乌斯·莫维利亚努", country: "罗马尼亚 (ROU)", age: 21, style: "左手弧圈突击" },
  { name: "克里斯蒂安·普莱泰亚", country: "罗马尼亚 (ROU)", age: 26, style: "正手暴冲型" },
  { name: "拉雷斯·西波斯", country: "罗马尼亚 (ROU)", age: 26, style: "两面稳健相持" },
  { name: "托米斯拉夫·普卡尔", country: "克罗地亚 (CRO)", age: 31, style: "高大力量型对拉" },
  { name: "安德烈·加奇纳", country: "克罗地亚 (CRO)", age: 40, style: "稳健两面相持" },
  { name: "菲利普·泽利科", country: "克罗地亚 (CRO)", age: 29, style: "近台快攻突击" },
  { name: "佐兰·普里莫拉茨", country: "克罗地亚 (CRO)", age: 57, style: "欧洲三大步法弧圈名将" },
  { name: "伊沃尔·班", country: "克罗地亚 (CRO)", age: 23, style: "左手两面快弧" },
  { name: "塞德里克·纽廷克", country: "比利时 (BEL)", age: 33, style: "左手两面快弧" },
  { name: "马丁·阿莱格罗", country: "比利时 (BEL)", age: 30, style: "近台中台相持" },
  { name: "让·米歇尔·塞弗", country: "比利时 (BEL)", age: 57, style: "乒坛铁人永不言弃拼命三郎" },
  { name: "阿德里安·拉森福斯", country: "比利时 (BEL)", age: 23, style: "快速突击进攻" },
  { name: "弗洛朗·朗比埃", country: "比利时 (BEL)", age: 28, style: "左手反胶快攻" },
  { name: "雅各布·迪亚斯", country: "波兰 (POL)", age: 31, style: "两面反胶弧圈" },
  { name: "米洛什·雷德齐姆斯基", country: "波兰 (POL)", age: 20, style: "快速相持新星" },
  { name: "马切伊·库比克", country: "波兰 (POL)", age: 23, style: "近台快速进攻" },
  { name: "萨穆埃尔·库尔齐茨基", country: "波兰 (POL)", age: 24, style: "反手大角度撕" },
  { name: "马雷克·巴多夫斯基", country: "波兰 (POL)", age: 29, style: "稳健攻防结合" },
  { name: "丹尼尔·戈拉克", country: "波兰 (POL)", age: 43, style: "左手控制型" },
  { name: "卢博米尔·扬卡里克", country: "捷克 (CZE)", age: 39, style: "正手中台中远台拉冲" },
  { name: "托马斯·波兰斯基", country: "捷克 (CZE)", age: 28, style: "两面弧圈相持" },
  { name: "吉日·马尔蒂科", country: "捷克 (CZE)", age: 27, style: "快速变线相持" },
  { name: "帕维尔·希鲁塞克", country: "捷克 (CZE)", age: 34, style: "正手进攻型" },
  { name: "彼得·科贝尔", country: "捷克 (CZE)", age: 55, style: "反手反撕翻挑鼻祖" },
  { name: "博扬·托基奇", country: "斯洛文尼亚 (SLO)", age: 45, style: "反手速度大师" },
  { name: "德尼·科祖尔", country: "斯洛文尼亚 (SLO)", age: 29, style: "两面快弧结合" },
  { name: "彼得·霍雷斯", country: "斯洛伐克 (SVK)", age: 32, style: "左手快速拉冲" },
  { name: "汪洋", country: "斯洛伐克 (SVK)", age: 32, style: "稳健削中反攻" },
  { name: "卢博米尔·皮斯特耶", country: "斯洛伐克 (SVK)", age: 42, style: "混双双打奇才" },
  { name: "亚历山大·瓦拉霍夫斯基", country: "斯洛伐克 (SVK)", age: 27, style: "两面反胶快攻" },
  { name: "米哈伊·博博西卡", country: "意大利 (ITA)", age: 40, style: "左手相持拉冲" },
  { name: "莱昂纳多·穆蒂", country: "意大利 (ITA)", age: 31, style: "两面反胶弧圈" },
  { name: "马泰奥·穆蒂", country: "意大利 (ITA)", age: 28, style: "快速进攻型" },
  { name: "约翰·奥耶巴德", country: "意大利 (ITA)", age: 26, style: "近台快攻突击" },
  { name: "卡洛·罗西", country: "意大利 (ITA)", age: 25, style: "快速相持型" },
  { name: "约翰·佩尔森", country: "丹麦 (DEN)", age: 34, style: "稳健防守相持" },
  { name: "托比亚斯·拉斯穆森", country: "丹麦 (DEN)", age: 29, style: "左手反胶快攻" },
  { name: "马丁·布赫·安德森", country: "丹麦 (DEN)", age: 25, style: "近台快攻突击" },
  { name: "米凯尔·辛德莱", country: "丹麦 (DEN)", age: 51, style: "中远台拉冲" },
  { name: "弗拉迪斯拉夫·乌苏", country: "摩尔多瓦 (MDA)", age: 25, style: "左手两面快弧" },
  { name: "安德烈·普图恩蒂卡", country: "摩尔多瓦 (MDA)", age: 27, style: "快速相持型" },
  { name: "本采·马约罗斯", country: "匈牙利 (HUN)", age: 29, style: "两面反胶弧圈" },
  { name: "亚当·苏迪", country: "匈牙利 (HUN)", age: 30, style: "左手双打快撕" },
  { name: "南多尔·埃克塞奇", country: "匈牙利 (HUN)", age: 29, style: "左手近台快弧" },
  { name: "彼得·亚历山德罗夫", country: "保加利亚 (BUL)", age: 24, style: "正手突击型" },
  { name: "约维察·佩特科维奇", country: "塞尔维亚 (SRB)", age: 28, style: "大力量拉冲" },
  { name: "亚历山大·卡拉卡塞维奇", country: "塞尔维亚 (SRB)", age: 50, style: "反手天才漫不经心大师" },
  { name: "马尔科·耶夫托维奇", country: "塞尔维亚 (SRB)", age: 39, style: "两面稳健相持" },
  { name: "兹索尔特·佩托", country: "塞尔维亚 (SRB)", age: 39, style: "快速相持型" },
  { name: "易卜拉欣·金杜兹", country: "土耳其 (TUR)", age: 28, style: "正手爆冲型" },
  { name: "阿卜杜拉·伊根勒", country: "土耳其 (TUR)", age: 27, style: "两面反胶快攻" },

  // --- 美洲各协会知名真实选手 ---
  { name: "马塞洛·阿吉雷", country: "巴拉圭 (PAR)", age: 33, style: "左手重炮弧圈" },
  { name: "阿尔贝托·米诺", country: "厄瓜多尔 (ECU)", age: 36, style: "中远台力量相持" },
  { name: "布莱恩·阿法纳多尔", country: "波多黎各 (PUR)", age: 34, style: "正手暴冲相持" },
  { name: "丹尼尔·冈萨雷斯", country: "波多黎各 (PUR)", age: 33, style: "近台快攻结合" },
  { name: "安赫尔·纳兰霍", country: "波多黎各 (PUR)", age: 22, style: "两面反胶快攻" },
  { name: "维克多·伊希", country: "巴西 (BRA)", age: 31, style: "两面均衡快弧" },
  { name: "吉列尔梅·特奥多罗", country: "巴西 (BRA)", age: 25, style: "正手突击进攻" },
  { name: "古斯塔沃·坪井", country: "巴西 (BRA)", age: 41, style: "左手速度大师" },
  { name: "埃里克·朱蒂", country: "巴西 (BRA)", age: 38, style: "稳健防守反击" },
  { name: "莱昂纳多·健二", country: "巴西 (BRA)", age: 22, style: "快速相持新秀" },
  { name: "雨果·奥亚马", country: "巴西 (BRA)", age: 57, style: "美洲传奇日直名宿" },
  { name: "王臻", country: "加拿大 (CAN)", age: 40, style: "近台快攻控制" },
  { name: "爱德华·李", country: "加拿大 (CAN)", age: 23, style: "两面反胶快弧" },
  { name: "西蒙·贝尔朗热", country: "加拿大 (CAN)", age: 22, style: "反手快速弹击" },
  { name: "马特奥·塞尔万特斯", country: "加拿大 (CAN)", age: 25, style: "稳健防守型" },
  { name: "尼古拉斯·伦布", country: "美国 (USA)", age: 27, style: "快速相持变线" },
  { name: "王皓平", country: "美国 (USA)", age: 34, style: "直拍横打进攻" },
  { name: "马科·马德里", country: "墨西哥 (MEX)", age: 39, style: "近台中台拉冲" },
  { name: "奥拉西奥·西富恩特斯", country: "阿根廷 (ARG)", age: 28, style: "正手凶狠发抢" },
  { name: "加斯顿·阿尔托", country: "阿根廷 (ARG)", age: 41, style: "两面反胶老将" },
  { name: "圣地亚哥·洛伦佐", country: "阿根廷 (ARG)", age: 24, style: "反手大力量反撕" },
  { name: "尼古拉斯·布尔戈斯", country: "智利 (CHI)", age: 24, style: "快速相持进攻" },
  { name: "古斯塔沃·戈麦斯", country: "智利 (CHI)", age: 30, style: "左手反胶快弧" },
  { name: "胡安·拉米雷斯", country: "智利 (CHI)", age: 36, style: "中远台对拉" },
  { name: "安迪·佩雷拉", country: "古巴 (CUB)", age: 36, style: "左手重炮弧圈" },
  { name: "豪尔赫·坎波斯", country: "古巴 (CUB)", age: 34, style: "正手爆冲型" },

  // --- 非洲各协会知名真实选手 ---
  { name: "博德·阿比奥顿", country: "尼日利亚 (NGR)", age: 45, style: "正手重炮相持" },
  { name: "奥拉吉德·奥莫塔约", country: "尼日利亚 (NGR)", age: 31, style: "高大力量进攻" },
  { name: "泰沃·马蒂", country: "尼日利亚 (NGR)", age: 21, style: "反手极速反撕" },
  { name: "塞贡·托里奥拉", country: "尼日利亚 (NGR)", age: 51, style: "七届奥运传奇老将" },
  { name: "夸德里·巴希尔", country: "尼日利亚 (NGR)", age: 27, style: "正手突击型" },
  { name: "艾哈迈德·萨利赫", country: "埃及 (EGY)", age: 46, style: "近台快攻相持" },
  { name: "优素福·阿卜杜勒·阿齐兹", country: "埃及 (EGY)", age: 27, style: "两面反胶快弧" },
  { name: "穆罕默德·埃尔贝亚利", country: "埃及 (EGY)", age: 36, style: "大力量拉冲" },
  { name: "巴德尔·穆斯塔法", country: "埃及 (EGY)", age: 22, style: "快速变线型" },
  { name: "阿姆鲁·雷达", country: "埃及 (EGY)", age: 32, style: "稳健防守型" },
  { name: "萨米·赫鲁夫", country: "阿尔及利亚 (ALG)", age: 37, style: "两面反胶相持" },
  { name: "迈赫迪·布洛萨", country: "阿尔及利亚 (ALG)", age: 29, style: "左手弧圈型" },
  { name: "拉尔比·鲍里亚", country: "阿尔及利亚 (ALG)", age: 42, style: "中远台对拉" },
  { name: "瓦西姆·埃西德", country: "突尼斯 (TUN)", age: 20, style: "快速突击新秀" },
  { name: "阿当·霍马姆", country: "突尼斯 (TUN)", age: 31, style: "两面反胶攻防" },
  { name: "易卜拉希马·迪奥", country: "塞内加尔 (SEN)", age: 43, style: "两面反胶控制" },

  // --- 亚洲及大洋洲各协会知名真实选手 ---
  { name: "萨蒂扬·格纳纳塞卡兰", country: "印度 (IND)", age: 33, style: "近台极速借力快推" },
  { name: "玛纳什·沙阿", country: "印度 (IND)", age: 24, style: "左手快速拉冲" },
  { name: "斯内希特·苏拉瓦朱拉", country: "印度 (IND)", age: 26, style: "正手爆冲型" },
  { name: "哈梅特·德赛", country: "印度 (IND)", age: 33, style: "稳健两面相持" },
  { name: "塔卡尔·马纳夫", country: "印度 (IND)", age: 26, style: "快速近台快攻" },
  { name: "安东尼·阿玛拉吉", country: "印度 (IND)", age: 39, style: "中远台拉冲" },
  { name: "桑尼尔·谢蒂", country: "印度 (IND)", age: 36, style: "左手弧圈进攻" },
  { name: "诺沙德·阿拉米扬", country: "伊朗 (IRI)", age: 34, style: "全球唯一纯反手魔术怪胶" },
  { name: "尼玛·阿拉米扬", country: "伊朗 (IRI)", age: 33, style: "两面暴力弧圈" },
  { name: "阿米尔·霍达伊", country: "伊朗 (IRI)", age: 27, style: "快速相持突击" },
  { name: "本雅明·法拉吉", country: "伊朗 (IRI)", age: 16, style: "战胜王楚钦之超新星" },
  { name: "阿夫申·诺鲁齐", country: "伊朗 (IRI)", age: 41, style: "近台快弧相持" },
  { name: "郭勇", country: "新加坡 (SGP)", age: 19, style: "左手全面快速攻防" },
  { name: "周哲宇", country: "新加坡 (SGP)", age: 30, style: "近台快弧相持" },
  { name: "冯耀恩", country: "新加坡 (SGP)", age: 23, style: "两面反胶进攻" },
  { name: "高宁", country: "新加坡 (SGP)", age: 43, style: "稳健防守大师" },
  { name: "杨子", country: "新加坡 (SGP)", age: 42, style: "左手近台快攻" },
  { name: "蔡劭恒", country: "新加坡 (SGP)", age: 25, style: "快速相持型" },
  { name: "梁振威", country: "马来西亚 (MAS)", age: 25, style: "正手爆冲型" },
  { name: "钟子毅", country: "马来西亚 (MAS)", age: 24, style: "两面快速攻防" },
  { name: "黄祺燊", country: "马来西亚 (MAS)", age: 22, style: "左手快弧相持" },
  { name: "沙克林·沙拉苏丁", country: "马来西亚 (MAS)", age: 40, style: "近台快攻型" },
  { name: "帕达萨克·坦维里亚维查库尔", country: "泰国 (THA)", age: 30, style: "左手两面反胶" },
  { name: "萨拉育·坦查罗恩", country: "泰国 (THA)", age: 28, style: "近台快攻突击" },
  { name: "苏帕纳特·威斯图马约", country: "泰国 (THA)", age: 24, style: "两面反胶快攻" },
  { name: "基里尔·格拉斯门科", country: "哈萨克斯坦 (KAZ)", age: 29, style: "反手大范围暴撕" },
  { name: "阿兰·库尔曼加利耶夫", country: "哈萨克斯坦 (KAZ)", age: 19, style: "快速突击新秀" },
  { name: "丹尼斯·若鲁捷夫", country: "哈萨克斯坦 (KAZ)", age: 28, style: "两面弧圈进攻" },
  { name: "阿里·阿尔哈德拉维", country: "沙特阿拉伯 (KSA)", age: 29, style: "两面反胶相持" },
  { name: "阿卜杜勒阿齐兹·布舒莱比", country: "沙特阿拉伯 (KSA)", age: 29, style: "快速进攻型" },
  { name: "林文政", country: "澳大利亚 (AUS)", age: 25, style: "两面反胶弧圈" },
  { name: "卢伟", country: "澳大利亚 (AUS)", age: 24, style: "近台快撕型" },
  { name: "鲍威尔·大卫", country: "澳大利亚 (AUS)", age: 35, style: "稳健攻防结合" },
  { name: "胡海明", country: "澳大利亚 (AUS)", age: 32, style: "左手两面快弧" },
  { name: "迪安·奇尼", country: "新西兰 (NZL)", age: 26, style: "两面反胶快攻" },
  { name: "阿尔弗雷德·德拉佩纳", country: "新西兰 (NZL)", age: 28, style: "近台快攻结合" }
];

const GLOBAL_LEGENDS_AND_PROS_SUPPLEMENT = [
  // 中国名宿与青年才俊
  { name: "何志文", country: "西班牙 (ESP)", age: 64, style: "左手正胶单面神挡" },
  { name: "塔里克·纳赛尔", country: "卡塔尔 (QAT)", age: 40, style: "稳健两面弧圈" },
  { name: "张本美和哥哥搭档", country: "日本 (JPN)", age: 20, style: "快速相持" },
  { name: "张本智和搭档", country: "日本 (JPN)", age: 21, style: "近台快弧" },
  { name: "陈卫星徒弟", country: "奥地利 (AUT)", age: 23, style: "现代削球" },
  { name: "李佳薇陪练", country: "新加坡 (SGP)", age: 30, style: "近台快攻" },
  { name: "黄镇廷师弟", country: "中国香港 (HKG)", age: 22, style: "直拍横打" },
  { name: "林昀儒师弟", country: "中国台北 (TPE)", age: 19, style: "左手反撕" },
  // 欧洲、美洲、非洲、亚洲各协会真实注册名录
  { name: "安德斯·埃林斯高", country: "丹麦 (DEN)", age: 27, style: "两面弧圈" },
  { name: "米克尔·辛德比", country: "丹麦 (DEN)", age: 26, style: "近台快撕" },
  { name: "马丁·卡茨曼", country: "捷克 (CZE)", age: 25, style: "防守反击" },
  { name: "翁德雷·巴尤尔", country: "捷克 (CZE)", age: 24, style: "正手进攻" },
  { name: "拉迪斯拉夫·斯梅卡尔", country: "捷克 (CZE)", age: 26, style: "中台拉冲" },
  { name: "扬·瓦尔查", country: "捷克 (CZE)", age: 23, style: "两面反胶" },
  { name: "菲利普·拉多维奇", country: "黑山 (MNE)", age: 26, style: "左手弧圈" },
  { name: "卢卡·巴基奇", country: "黑山 (MNE)", age: 27, style: "两面快攻" },
  { name: "伊利尔·普雷斯蒂", country: "科索沃 (KOS)", age: 23, style: "近台进攻" },
  { name: "法捷耶夫·安东", country: "乌克兰 (UKR)", age: 28, style: "中远台相持" },
  { name: "亚罗斯拉夫·日穆坚科", country: "乌克兰 (UKR)", age: 38, style: "两面弧圈" },
  { name: "叶夫根·普里谢帕", country: "乌克兰 (UKR)", age: 41, style: "左手快拉" },
  { name: "维克托·叶菲莫夫", country: "乌克兰 (UKR)", age: 37, style: "正手爆冲" },
  { name: "德米特罗·亚奇塞克", country: "乌克兰 (UKR)", age: 22, style: "反手快撕" },
  { name: "约瑟夫·西蒙奇克", country: "捷克 (CZE)", age: 35, style: "削球防守" },
  { name: "托马什·科内奇尼", country: "捷克 (CZE)", age: 40, style: "正手中台拉" },
  { name: "达维德·科内奇尼", country: "捷克 (CZE)", age: 23, style: "两面相持" },
  { name: "托马什·特雷格勒", country: "捷克 (CZE)", age: 36, style: "近台快弧" },
  { name: "马蒂亚斯·丹尼尔森", country: "瑞典 (SWE)", age: 23, style: "反手快撕" },
  { name: "安德斯·佩尔森", country: "瑞典 (SWE)", age: 24, style: "正手突击" },
  { name: "塞巴斯蒂安·洛塞尔", country: "瑞典 (SWE)", age: 31, style: "稳健相持" },
  { name: "亚历山大·弗朗茨", country: "瑞典 (SWE)", age: 25, style: "两面弧圈" },
  { name: "佩尔·桑德斯特伦", country: "瑞典 (SWE)", age: 22, style: "近台快攻" },
  { name: "约翰·松德奎斯特", country: "瑞典 (SWE)", age: 28, style: "左手中台拉" },
  { name: "亨利克·伦奎斯特", country: "瑞典 (SWE)", age: 24, style: "正手爆冲" },
  { name: "马格努斯·莫勒", country: "丹麦 (DEN)", age: 25, style: "两面进攻" },
  { name: "克里斯蒂安·孔斯高", country: "丹麦 (DEN)", age: 26, style: "稳健防守" },
  { name: "索伦·特鲁尔斯", country: "丹麦 (DEN)", age: 23, style: "反手突击" },
  { name: "卡斯帕·文瑟尔", country: "丹麦 (DEN)", age: 22, style: "快速相持" },
  { name: "帕特里克·霍尔姆", country: "丹麦 (DEN)", age: 24, style: "正手快拉" },
  { name: "卢卡斯·罗曼", country: "法国 (FRA)", age: 23, style: "左手相持" },
  { name: "格雷瓜尔·让", country: "法国 (FRA)", age: 32, style: "两面反胶" },
  { name: "阿诺·蒂尔曼特", country: "法国 (FRA)", age: 28, style: "中远台拉冲" },
  { name: "巴斯蒂安·杜邦", country: "法国 (FRA)", age: 26, style: "快速变线" },
  { name: "雨果·德尚", country: "法国 (FRA)", age: 22, style: "反手弹击" },
  { name: "托马斯·勒布雷顿", country: "法国 (FRA)", age: 36, style: "稳健相持" },
  { name: "马克西姆·博舍", country: "法国 (FRA)", age: 29, style: "正手进攻" },
  { name: "罗曼·洛伦茨", country: "法国 (FRA)", age: 34, style: "两面弧圈" },
  { name: "亚历山大·卡辛", country: "法国 (FRA)", age: 27, style: "近台快攻" },
  { name: "本杰明·布罗西尔", country: "法国 (FRA)", age: 34, style: "反手快撕" },
  { name: "扬尼克·鲍曼", country: "德国 (GER)", age: 26, style: "稳健防守" },
  { name: "伦纳特·韦尔", country: "德国 (GER)", age: 24, style: "两面快攻" },
  { name: "马尔特·范·贝尔森", country: "德国 (GER)", age: 25, style: "正手中台拉" },
  { name: "弗洛里安·布伦", country: "德国 (GER)", age: 27, style: "快速变线" },
  { name: "托尔斯滕·梅茨", country: "德国 (GER)", age: 29, style: "大力量拉冲" },
  { name: "马库斯·斯特格", country: "德国 (GER)", age: 24, style: "反手快弹" },
  { name: "卢卡斯·菲利普", country: "德国 (GER)", age: 23, style: "近台快撕" },
  { name: "尼克·维泽尔", country: "德国 (GER)", age: 22, style: "两面反胶" },
  { name: "费利克斯·韦斯特法尔", country: "德国 (GER)", age: 25, style: "稳健相持" },
  { name: "塞巴斯蒂安·博尔", country: "德国 (GER)", age: 26, style: "左手快弧" },
  { name: "吉安卢卡·瓦尔蒂", country: "意大利 (ITA)", age: 24, style: "快速相持" },
  { name: "马尔科·雷奇·戴索利", country: "意大利 (ITA)", age: 41, style: "削球防守" },
  { name: "达尼埃莱·平托", country: "意大利 (ITA)", age: 28, style: "两面弧圈" },
  { name: "安东尼奥·阿马托", country: "意大利 (ITA)", age: 27, style: "正手突击" },
  { name: "尼科洛·皮奇林", country: "意大利 (ITA)", age: 26, style: "近台快撕" },
  { name: "毛里齐奥·费兰德斯", country: "意大利 (ITA)", age: 23, style: "反手快弹" },
  { name: "托马索·乔万内蒂", country: "意大利 (ITA)", age: 22, style: "快速变线" },
  { name: "安德烈亚·普佩", country: "意大利 (ITA)", age: 21, style: "左手攻防" },
  { name: "西蒙尼·索菲亚", country: "意大利 (ITA)", age: 25, style: "两面反胶" },
  { name: "费德里科·瓦兰蒂", country: "意大利 (ITA)", age: 24, style: "稳健拉冲" },
  { name: "琼·马西普", country: "西班牙 (ESP)", age: 26, style: "两面弧圈" },
  { name: "卡洛斯·卡瓦列罗", country: "西班牙 (ESP)", age: 29, style: "稳健相持" },
  { name: "马克·杜兰", country: "西班牙 (ESP)", age: 39, style: "近台快攻" },
  { name: "阿尔贝托·利洛", country: "西班牙 (ESP)", age: 24, style: "左手快攻" },
  { name: "米格尔·维尔切斯", country: "西班牙 (ESP)", age: 28, style: "正手暴冲" },
  { name: "拉斐尔·德·拉斯·埃拉斯", country: "西班牙 (ESP)", age: 23, style: "两面反胶" },
  { name: "诺伯特·陶伯", country: "西班牙 (ESP)", age: 25, style: "快速变线" },
  { name: "丹尼尔·帕洛玛雷斯", country: "西班牙 (ESP)", age: 22, style: "反手快撕" },
  { name: "阿诺·弗朗西斯科", country: "西班牙 (ESP)", age: 24, style: "近台进攻" },
  { name: "塞尔吉奥·戈麦斯", country: "西班牙 (ESP)", age: 23, style: "中台中远台" },
  { name: "蒂亚戈·列瓦雅奇", country: "塞尔维亚 (SRB)", age: 25, style: "左手重炮" },
  { name: "内曼尼亚·迪米特里耶维奇", country: "塞尔维亚 (SRB)", age: 24, style: "正手进攻" },
  { name: "佩塔尔·克尔斯蒂奇", country: "塞尔维亚 (SRB)", age: 28, style: "两面弧圈" },
  { name: "斯特凡·科斯塔季诺维奇", country: "塞尔维亚 (SRB)", age: 31, style: "稳健防守" },
  { name: "弗拉基米尔·拉多尼奇", country: "塞尔维亚 (SRB)", age: 35, style: "削中反攻" },
  { name: "达里奥·科祖尔", country: "斯洛文尼亚 (SLO)", age: 27, style: "快速相持" },
  { name: "彼得·弗雷利赫", country: "斯洛文尼亚 (SLO)", age: 23, style: "两面进攻" },
  { name: "蒂伦·科尔维茨", country: "斯洛文尼亚 (SLO)", age: 26, style: "近台快撕" },
  { name: "亚卡·戈罗佩夫塞克", country: "斯洛文尼亚 (SLO)", age: 24, style: "稳健相持" },
  { name: "米哈·波多布尼克", country: "斯洛文尼亚 (SLO)", age: 22, style: "正手突击" },
  { name: "加布里埃尔·卡梅伦", country: "澳大利亚 (AUS)", age: 24, style: "两面反胶" },
  { name: "哈维尔·迪克森", country: "澳大利亚 (AUS)", age: 23, style: "近台快攻" },
  { name: "罗恩·汤普森", country: "澳大利亚 (AUS)", age: 26, style: "正手爆冲" },
  { name: "卢克·卡特", country: "澳大利亚 (AUS)", age: 25, style: "中远台拉" },
  { name: "奥利弗·格林", country: "澳大利亚 (AUS)", age: 22, style: "快速突击" },
  { name: "内森·霍尔", country: "澳大利亚 (AUS)", age: 27, style: "稳健相持" },
  { name: "马修·贝克", country: "澳大利亚 (AUS)", age: 29, style: "左手进攻" },
  { name: "利亚姆·怀特", country: "澳大利亚 (AUS)", age: 21, style: "反手弹击" },
  { name: "蒂姆·克拉克", country: "澳大利亚 (AUS)", age: 28, style: "两面快弧" },
  { name: "丹尼尔·沃德", country: "澳大利亚 (AUS)", age: 23, style: "快速攻防" },
  { name: "乔纳森·贝克", country: "新西兰 (NZL)", age: 27, style: "正手进攻" },
  { name: "马修·亨特", country: "新西兰 (NZL)", age: 25, style: "稳健相持" },
  { name: "本·斯科特", country: "新西兰 (NZL)", age: 24, style: "两面反胶" },
  { name: "哈利·帕克", country: "新西兰 (NZL)", age: 22, style: "近台快攻" },
  { name: "托马斯·亚当斯", country: "新西兰 (NZL)", age: 26, style: "反手快撕" },
  { name: "杰克·威尔逊", country: "新西兰 (NZL)", age: 23, style: "中远台对拉" },
  { name: "山姆·泰勒", country: "新西兰 (NZL)", age: 28, style: "左手快弧" },
  { name: "威廉·罗宾逊", country: "新西兰 (NZL)", age: 21, style: "快速突击" },
  { name: "卢卡斯·金", country: "新西兰 (NZL)", age: 25, style: "稳健防守" },
  { name: "埃里克·米勒", country: "新西兰 (NZL)", age: 24, style: "两面相持" }
];

const NAME_PARTS_DATABASE = {
  // 中国 (CHN)：姓氏 + 2个字随机组合（如 樊 + 楚 + 东 -> 樊楚东 / 王 + 诗 + 豪 -> 王诗豪）
  CHN: {
    surnames: ["王", "林", "樊", "梁", "马", "向", "周", "徐", "袁", "陈", "黄", "温", "薛", "孙", "刘", "曹", "曾", "陶", "祝", "朱", "张", "郝", "严", "高", "牛", "全", "赛", "胡", "李", "郑", "程", "宋", "房", "孔"],
    givenChars: ["楚", "钦", "诗", "栋", "振", "东", "靖", "崑", "龙", "鹏", "启", "豪", "瑛", "彬", "励", "岑", "垣", "宇", "友", "政", "瑞", "博", "飞", "闻", "硕", "巍", "勋", "阳", "超", "帅", "玘", "松", "涛", "志", "杰", "冠", "凯", "洋", "晨", "皓", "廷", "天"]
  },
  // 日本 (JPN)：真实日本姓 + 真实日本名重组（如 松岛 + 智和 -> 松岛智和 / 户上 + 辉空 -> 户上辉空）
  JPN: {
    surnames: ["张本", "松岛", "户上", "篠塚", "宇田", "田中", "吉村", "及川", "滨田", "吉山", "萩原", "木造", "森园", "神", "英田", "水谷", "丹羽", "大岛", "松平", "吉田", "村松", "岸川", "上田", "有延", "坂井", "川上"],
    givens: ["智和", "辉空", "隼辅", "大登", "幸矢", "佑汰", "真晴", "瑞基", "一辉", "僚一", "和希", "勇人", "政崇", "巧也", "理志", "隼", "孝希", "祐哉", "健太", "雅己", "雄斗", "圣也", "仁", "大梦", "雄飞", "流星"]
  },
  // 韩国 (KOR)：真实韩国姓 + 真实韩国名重组（如 郑 + 禹珍 -> 郑禹珍 / 李 + 晙诚 -> 李晙诚）
  KOR: {
    surnames: ["李", "安", "赵", "张", "林", "吴", "朴", "姜", "金", "郑", "柳", "朱", "丁", "徐", "尹", "白", "黄"],
    givens: ["尚洙", "宰贤", "大成", "禹珍", "钟勋", "晙诚", "胜敏", "康贤", "东秀", "敏赫", "奎炫", "荣植", "承敏", "世爀", "祥恩", "东贤", "浩锡", "泽洙", "南奎", "廷佑"]
  },
  // 中国港台 (TPE / HKG)
  TPE_HKG: {
    surnames: ["林", "高", "庄", "冯", "黄", "廖", "陈", "张", "洪", "郭", "何", "姚", "关", "李", "鲍", "苏", "唐", "江"],
    givens: ["昀儒", "承睿", "智渊", "翊新", "彦诚", "振珽", "建安", "佑安", "敬恺", "冠宏", "兆恒", "钧杰", "颢桦", "钧涛", "文皓", "汉铭", "奕文", "镇廷", "天一"]
  },
  // 马来西亚 (MAS)：以马来西亚华裔常见姓氏 + 双字名组合为主（如 梁振威 / 钟子毅）
  MAS: {
    surnames: ["陈", "林", "黄", "李", "张", "王", "吴", "刘", "蔡", "杨", "郑", "谢", "梁", "钟", "曾", "许", "叶", "罗", "何", "邓"],
    givens: ["振威", "子毅", "祺燊", "俊贤", "伟强", "俊豪", "家荣", "志强", "俊杰", "健文", "俊威", "伟伦", "家豪", "俊宇", "文昌", "国伟", "耀祖", "俊瑋", "伟杰", "泽豪"]
  },
  // 泰国 (THA)：泰式前名 + 姓氏组合
  THA: {
    firstNames: ["他农", "蓬萨克", "素坤", "他威", "阿披瓦", "威拉", "帕塔拉", "颂猜", "纳塔波", "钦纳瓦"],
    lastNames: ["猜耶波恩", "素帕差", "汶纳格", "他农猜", "颂克兰", "帕塔纳", "威拉冯", "阿努颂", "占塔拉", "沙田"]
  },
  // 印度 (IND)：印度前名 + 姓氏组合
  IND: {
    firstNames: ["沙拉斯", "阿肖克", "阿尼尔", "拉胡尔", "阿米特", "维克拉姆", "阿尔琼", "萨米尔", "罗希特", "苏雷什"],
    lastNames: ["卡玛尔", "顾普塔", "沙玛", "辛格", "库马尔", "帕特尔", "梅塔", "德赛", "拉奥", "查特吉"]
  },
  // 中东/北非/土耳其 (MENA：埃及、阿尔及利亚、突尼斯、沙特、卡塔尔、伊朗、土耳其)
  MENA: {
    firstNames: ["奥马尔", "卡里姆", "优素福", "艾哈迈德", "塔里克", "哈立德", "礼萨", "阿里", "侯赛因", "埃姆雷", "穆罕默德", "布拉克"],
    lastNames: ["阿萨尔", "曼苏尔", "拉希德", "哈桑", "谢里夫", "纳赛尔", "扎德", "拉希米", "侯赛尼", "于杰尔", "德米尔", "沙欣"]
  },
  // 西非 (尼日利亚、塞内加尔)
  AFRICA_W: {
    firstNames: ["夸德里", "奥卢", "钦耶姆", "阿德", "巴巴图恩德", "马马杜", "伊斯梅拉", "阿卜杜"],
    lastNames: ["阿鲁纳", "恩迪亚耶", "迪奥普", "姆本格", "图雷", "迪亚涅", "奥孔克沃", "法耶"]
  },
  // 拉丁美洲+西班牙 (阿根廷、墨西哥、智利、古巴、巴拉圭、厄瓜多尔、波多黎各、西班牙)
  LATAM: {
    firstNames: ["迭戈", "巴勃罗", "卡洛斯", "路易斯", "费尔南多", "阿尔瓦罗", "哈维尔", "马里奥", "安德烈斯", "伊格纳西奥"],
    lastNames: ["罗伯勒斯", "冈萨雷斯", "桑切斯", "罗德里格斯", "加西亚", "马丁内斯", "洛佩兹", "埃尔南德斯", "迪亚斯", "莫拉莱斯"]
  },
  // 葡语系 (葡萄牙、巴西)
  LUSO: {
    firstNames: ["马科斯", "雨果", "布鲁诺", "里卡多", "保罗", "费利佩", "罗德里戈", "古斯塔沃"],
    lastNames: ["弗雷塔斯", "卡尔德拉诺", "席尔瓦", "桑托斯", "佩雷拉", "科斯塔", "奥利维拉", "阿劳霍"]
  },
  // 法语系 (法国、比利时)
  FRANCO: {
    firstNames: ["费利克斯", "艾利克斯", "西蒙", "雨果", "卢卡", "安托万", "马蒂厄", "皮埃尔"],
    lastNames: ["勒布伦", "高茨", "杜邦", "马丁", "贝尔纳", "罗兰", "勒鲁瓦", "菲利普"]
  },
  // 德语系 (德国、奥地利)
  GERMANIC: {
    firstNames: ["帕特里克", "蒂姆", "贝内迪克特", "马克斯", "扬", "弗洛里安", "卢卡斯", "斯特凡"],
    lastNames: ["弗朗西斯卡", "波尔", "杜达", "施密特", "穆勒", "韦伯", "克莱因", "霍夫曼"]
  },
  // 北欧 (瑞典、丹麦)
  NORDIC: {
    firstNames: ["特鲁斯", "安东", "马蒂亚斯", "约纳坦", "埃里克", "拉斯穆斯", "尼尔斯", "奥斯卡"],
    lastNames: ["莫雷加德", "卡尔伯格", "法尔克", "格罗特", "尼尔森", "安德森", "拉尔森", "彼得森"]
  },
  // 英语系 (英格兰、美国、澳大利亚、加拿大、新西兰)
  ANGLO: {
    firstNames: ["利亚姆", "卡纳克", "杰克", "瑞安", "卢克", "亚当", "康纳", "泰勒"],
    lastNames: ["皮切福德", "贾哈", "史密斯", "约翰逊", "泰勒", "威尔逊", "摩尔", "贝克"]
  },
  // 意大利
  ITALIC: {
    firstNames: ["马可", "卢卡", "安德烈亚", "亚历山德罗", "达尼埃莱", "詹卢卡"],
    lastNames: ["罗西", "里齐", "贝鲁奇", "加利", "费拉里", "布鲁诺"]
  },
  // 希腊
  HELLENIC: {
    firstNames: ["帕纳吉奥蒂斯", "乔治斯", "迪米特里斯", "扬尼斯", "尼科斯"],
    lastNames: ["吉奥尼斯", "帕帕佐普洛斯", "康斯坦丁诺", "格奥尔基乌", "瓦西利乌"]
  },
  // 中东欧/斯拉夫系 (波兰、捷克、斯洛伐克、克罗地亚、塞尔维亚、斯洛文尼亚、乌克兰、保加利亚、摩尔多瓦、科索沃、黑山、匈牙利、罗马尼亚、哈萨克斯坦)
  SLAVIC_EU: {
    firstNames: ["卢博米尔", "托米斯拉夫", "米洛什", "达科", "雅各布", "帕维尔", "马雷克", "维克多", "安杰伊", "斯拉夫科"],
    lastNames: ["约奇克", "普卡尔", "纽廷克", "雷德齐姆斯基", "诺瓦克", "科瓦奇", "波波夫", "科瓦尔斯基", "霍瓦特", "杜布罗夫斯基"]
  },
  // 兜底：暂未归类的其他国家/地区
  WESTERN: {
    firstNames: ["塞德里克", "雅各布", "保罗", "丹尼尔", "若昂", "爱德华", "安德烈", "加斯顿", "马塞洛", "基里尔"],
    lastNames: ["金克霍尔", "哈贝松", "格拉尔多", "约内斯库", "加奇纳", "阿吉雷", "格拉斯门科", "阿拉米扬", "德赛", "坦维里亚维查库尔"]
  }
};

// 国家代码 -> 姓名库分组映射（用于 generateUniqueRookieName）
// special: 使用东亚式生成规则（姓+名直接拼接，无分隔符）
// pool: 使用"名·姓"式生成规则（NAME_PARTS_DATABASE 中对应的 firstNames/lastNames）
const COUNTRY_NAME_BUCKET_MAP = {
  CHN: { kind: "special", key: "CHN" },
  JPN: { kind: "special", key: "JPN" },
  KOR: { kind: "special", key: "KOR" },
  TPE: { kind: "special", key: "TPE_HKG" },
  HKG: { kind: "special", key: "TPE_HKG" },
  MAS: { kind: "special", key: "MAS" },
  SGP: { kind: "special", key: "MAS" },
  THA: { kind: "pool", key: "THA" },
  IND: { kind: "pool", key: "IND" },
  EGY: { kind: "pool", key: "MENA" },
  ALG: { kind: "pool", key: "MENA" },
  TUN: { kind: "pool", key: "MENA" },
  KSA: { kind: "pool", key: "MENA" },
  QAT: { kind: "pool", key: "MENA" },
  IRI: { kind: "pool", key: "MENA" },
  TUR: { kind: "pool", key: "MENA" },
  NGR: { kind: "pool", key: "AFRICA_W" },
  SEN: { kind: "pool", key: "AFRICA_W" },
  ARG: { kind: "pool", key: "LATAM" },
  MEX: { kind: "pool", key: "LATAM" },
  CHI: { kind: "pool", key: "LATAM" },
  CUB: { kind: "pool", key: "LATAM" },
  PAR: { kind: "pool", key: "LATAM" },
  ECU: { kind: "pool", key: "LATAM" },
  PUR: { kind: "pool", key: "LATAM" },
  ESP: { kind: "pool", key: "LATAM" },
  POR: { kind: "pool", key: "LUSO" },
  BRA: { kind: "pool", key: "LUSO" },
  FRA: { kind: "pool", key: "FRANCO" },
  BEL: { kind: "pool", key: "FRANCO" },
  GER: { kind: "pool", key: "GERMANIC" },
  AUT: { kind: "pool", key: "GERMANIC" },
  SWE: { kind: "pool", key: "NORDIC" },
  DEN: { kind: "pool", key: "NORDIC" },
  ENG: { kind: "pool", key: "ANGLO" },
  USA: { kind: "pool", key: "ANGLO" },
  AUS: { kind: "pool", key: "ANGLO" },
  CAN: { kind: "pool", key: "ANGLO" },
  NZL: { kind: "pool", key: "ANGLO" },
  ITA: { kind: "pool", key: "ITALIC" },
  GRE: { kind: "pool", key: "HELLENIC" },
  POL: { kind: "pool", key: "SLAVIC_EU" },
  CZE: { kind: "pool", key: "SLAVIC_EU" },
  SVK: { kind: "pool", key: "SLAVIC_EU" },
  CRO: { kind: "pool", key: "SLAVIC_EU" },
  SRB: { kind: "pool", key: "SLAVIC_EU" },
  SLO: { kind: "pool", key: "SLAVIC_EU" },
  UKR: { kind: "pool", key: "SLAVIC_EU" },
  BUL: { kind: "pool", key: "SLAVIC_EU" },
  MDA: { kind: "pool", key: "SLAVIC_EU" },
  KOS: { kind: "pool", key: "SLAVIC_EU" },
  MNE: { kind: "pool", key: "SLAVIC_EU" },
  HUN: { kind: "pool", key: "SLAVIC_EU" },
  ROU: { kind: "pool", key: "SLAVIC_EU" },
  KAZ: { kind: "pool", key: "SLAVIC_EU" }
};