const COUNTRIES_GLOBAL = [
  "中国 (CHN)", "日本 (JPN)", "法国 (FRA)", "德国 (GER)", "瑞典 (SWE)", "韩国 (KOR)", 
  "中国台北 (TPE)", "巴西 (BRA)", "尼日利亚 (NGR)", "英格兰 (ENG)", "葡萄牙 (POR)", 
  "埃及 (EGY)", "斯洛文尼亚 (SLO)", "中国香港 (HKG)", "印度 (IND)", "美国 (USA)", 
  "丹麦 (DEN)", "新加坡 (SGP)", "澳大利亚 (AUS)", "奥地利 (AUT)", "罗马尼亚 (ROU)",
  "波兰 (POL)", "捷克 (CZE)", "斯洛伐克 (SVK)", "克罗地亚 (CRO)", "塞尔维亚 (SRB)",
  "意大利 (ITA)", "西班牙 (ESP)", "比利时 (BEL)", "希腊 (GRE)", "匈牙利 (HUN)",
  "加拿大 (CAN)", "智利 (CHI)", "阿根廷 (ARG)", "波多黎各 (PUR)", "古巴 (CUB)",
  "哈萨克斯坦 (KAZ)", "泰国 (THA)", "马来西亚 (MAS)", "伊朗 (IRI)", "沙特阿拉伯 (KSA)",
  "土耳其 (TUR)", "阿尔及利亚 (ALG)", "突尼斯 (TUN)", "塞内加尔 (SEN)", "新西兰 (NZL)",
  "乌克兰 (UKR)", "保加利亚 (BUL)", "卡塔尔 (QAT)", "厄瓜多尔 (ECU)", "墨西哥 (MEX)",
  "巴拉圭 (PAR)", "摩尔多瓦 (MDA)", "科索沃 (KOS)", "黑山 (MNE)"
];

const BASE_REAL_STARS_CN = [
  { name: "汪楚秦", country: "中国 (CHN)", points: 8200, age: 26, style: "横板两面暴力弧圈", basePow: 92, injury: "健康", prevRank: 1 },
  { name: "琳恃东", country: "中国 (CHN)", points: 7650, age: 21, style: "横板反手快撕大师", basePow: 90, injury: "健康", prevRank: 2 },
  { name: "范镇栋", country: "中国 (CHN)", points: 6900, age: 29, style: "横板终极重炮对拉", basePow: 93, injury: "健康", prevRank: 3 },
  { name: "于国·卡二得拉诺", country: "巴西 (BRA)", points: 5800, age: 30, style: "中远台大力量进攻", basePow: 88, injury: "健康", prevRank: 4 },
  { name: "菲历可斯·雷布伦", country: "法国 (FRA)", points: 5400, age: 20, style: "直拍横打极速突击", basePow: 87, injury: "健康", prevRank: 5 },
  { name: "长本致何", country: "日本 (JPN)", points: 5150, age: 23, style: "近台超强速度反撕", basePow: 86, injury: "健康", prevRank: 6 },
  { name: "特陆斯·默勒贾得", country: "瑞典 (SWE)", points: 4800, age: 24, style: "六边形异形拍灵动变线", basePow: 85, injury: "健康", prevRank: 7 },
  { name: "亮景崑", country: "中国 (CHN)", points: 4500, age: 30, style: "横板重炮大路相持", basePow: 86, injury: "健康", prevRank: 8 },
  { name: "琳昀儒", country: "中国台北 (TPE)", points: 4100, age: 25, style: "反手黄金拧拉大师", basePow: 84, injury: "健康", prevRank: 9 },
  { name: "帕特李科·辅朗熙斯卡", country: "德国 (GER)", points: 3400, age: 34, style: "欧洲大力量弧圈", basePow: 82, injury: "健康", prevRank: 10 },
  { name: "玛隆", country: "中国 (CHN)", points: 3350, age: 38, style: "六边形终极掌控", basePow: 91, injury: "膝盖劳损", prevRank: 11 },
  { name: "岸栋·卡二博各", country: "瑞典 (SWE)", points: 2900, age: 29, style: "近中台快攻结合弧圈", basePow: 81, injury: "健康", prevRank: 12 },
  { name: "萩当", country: "德国 (GER)", points: 2850, age: 30, style: "传统直拍正胶与横打", basePow: 80, injury: "健康", prevRank: 13 },
  { name: "搭可·跃启科", country: "斯洛文尼亚 (SLO)", points: 2700, age: 28, style: "反手暴冲弹击型", basePow: 80, injury: "健康", prevRank: 14 },
  { name: "夸得李·阿陆纳", country: "尼日利亚 (NGR)", points: 2450, age: 38, style: "正手超强重炮手", basePow: 79, injury: "健康", prevRank: 15 },
  { name: "爱历可斯·雷布伦", country: "法国 (FRA)", points: 2300, age: 23, style: "神经刀暴力发抢", basePow: 79, injury: "健康", prevRank: 16 },
  { name: "迪木·卜二", country: "德国 (GER)", points: 1950, age: 45, style: "旋转弧圈艺术大师", basePow: 82, injury: "老伤反复", prevRank: 17 },
  { name: "胡尚荪福", country: "日本 (JPN)", points: 1900, age: 25, style: "两面快弧进攻型", basePow: 78, injury: "健康", prevRank: 18 },
  { name: "宋道辉孔", country: "日本 (JPN)", points: 1850, age: 19, style: "左手两面反胶快攻", basePow: 77, injury: "健康", prevRank: 19 },
  { name: "高诚瑞", country: "中国台北 (TPE)", points: 1750, age: 21, style: "近台快攻突击型", basePow: 76, injury: "健康", prevRank: 20 },
  { name: "奥恰罗弗", country: "德国 (GER)", points: 1700, age: 38, style: "潜艇发球暴力反手", basePow: 80, injury: "背部劳损", prevRank: 21 },
  { name: "庄植垣", country: "中国台北 (TPE)", points: 1600, age: 45, style: "近台快攻老将", basePow: 76, injury: "健康", prevRank: 22 },
  { name: "希梦·高茨", country: "法国 (FRA)", points: 1550, age: 32, style: "魔术师手感放高球", basePow: 77, injury: "健康", prevRank: 23 },
  { name: "卡纳可·家哈", country: "美国 (USA)", points: 1450, age: 26, style: "稳健防守反击型", basePow: 75, injury: "健康", prevRank: 24 },
  { name: "玛地雅斯·发二科", country: "瑞典 (SWE)", points: 1400, age: 35, style: "正手正胶异质快攻", basePow: 76, injury: "健康", prevRank: 25 },
  { name: "蓓内蒂科特·杜大", country: "德国 (GER)", points: 1350, age: 32, style: "左手中台重炮对拉", basePow: 76, injury: "健康", prevRank: 26 },
  { name: "黄臻珽", country: "中国香港 (HKG)", points: 1300, age: 35, style: "传统直拍横打快变", basePow: 75, injury: "健康", prevRank: 27 },
  { name: "黎上祝", country: "韩国 (KOR)", points: 1250, age: 36, style: "近台拼命三郎狂攻", basePow: 75, injury: "健康", prevRank: 28 },
  { name: "岸哉贤", country: "韩国 (KOR)", points: 1200, age: 27, style: "两面弧圈相持型", basePow: 74, injury: "健康", prevRank: 29 },
  { name: "兆达承", country: "韩国 (KOR)", points: 1150, age: 24, style: "左手快弧结合变线", basePow: 74, injury: "健康", prevRank: 30 },
  { name: "长钰振", country: "韩国 (KOR)", points: 1100, age: 31, style: "正手狂奔大范围暴冲", basePow: 75, injury: "健康", prevRank: 31 },
  { name: "琳塚逊", country: "韩国 (KOR)", points: 1080, age: 29, style: "左手两面拧拉突击", basePow: 75, injury: "健康", prevRank: 32 },
  { name: "孝中搭登", country: "日本 (JPN)", points: 1050, age: 22, style: "左手灵巧落点相持", basePow: 73, injury: "健康", prevRank: 33 },
  { name: "羽天星恃", country: "日本 (JPN)", points: 1020, age: 25, style: "左手近台前冲弧圈", basePow: 74, injury: "健康", prevRank: 34 },
  { name: "天钟优太", country: "日本 (JPN)", points: 980, age: 26, style: "稳健两面均衡防守", basePow: 72, injury: "健康", prevRank: 35 },
  { name: "季村臻晴", country: "日本 (JPN)", points: 960, age: 33, style: "勾手发球正手反拉", basePow: 73, injury: "健康", prevRank: 36 },
  { name: "祥澎", country: "中国 (CHN)", points: 950, age: 23, style: "正手大角度反拉爆冲", basePow: 76, injury: "健康", prevRank: 37 },
  { name: "周崎皓", country: "中国 (CHN)", points: 920, age: 29, style: "神经刀暴力弧圈流", basePow: 76, injury: "健康", prevRank: 38 },
  { name: "许英滨", country: "中国 (CHN)", points: 890, age: 25, style: "近台快弧相持型", basePow: 73, injury: "健康", prevRank: 39 },
  { name: "园历岑", country: "中国 (CHN)", points: 870, age: 26, style: "左手两面快撕变线", basePow: 73, injury: "健康", prevRank: 40 },
  { name: "晨渊羽", country: "中国 (CHN)", points: 850, age: 21, style: "两面弧圈新生代", basePow: 72, injury: "健康", prevRank: 41 },
  { name: "黄祐正", country: "中国 (CHN)", points: 830, age: 21, style: "反手速度快撕型", basePow: 71, injury: "健康", prevRank: 42 },
  { name: "文睿波", country: "中国 (CHN)", points: 800, age: 19, style: "反手大力量暴冲", basePow: 71, injury: "健康", prevRank: 43 },
  { name: "薛菲", country: "中国 (CHN)", points: 780, age: 27, style: "直拍横打传统继承", basePow: 72, injury: "健康", prevRank: 44 },
  { name: "李雅穆·皮切弗得", country: "英格兰 (ENG)", points: 760, age: 33, style: "反手超音速反撕", basePow: 75, injury: "健康", prevRank: 45 },
  { name: "玛可斯·夫勒塔斯", country: "葡萄牙 (POR)", points: 740, age: 38, style: "左手稳健相持大师", basePow: 74, injury: "健康", prevRank: 46 },
  { name: "跃纳坦·哥洛特", country: "丹麦 (DEN)", points: 720, age: 34, style: "左手大范围相持", basePow: 73, injury: "健康", prevRank: 47 },
  { name: "阿二瓦洛·洛卜雷斯", country: "西班牙 (ESP)", points: 700, age: 35, style: "左手弧圈旋转型", basePow: 72, injury: "健康", prevRank: 48 },
  { name: "奥玛二·阿萨二", country: "埃及 (EGY)", points: 680, age: 35, style: "欧洲型高大防守相持", basePow: 74, injury: "健康", prevRank: 49 },
  { name: "沙拉斯·卡马二", country: "印度 (IND)", points: 650, age: 44, style: "高大力量弧圈老将", basePow: 73, injury: "健康", prevRank: 50 }
];

const REAL_PLAYERS_EXTENDED_DATABASE = [
  // --- 中国 (CHN) ---
  { name: "许陈郝", country: "中国 (CHN)", age: 31, style: "横板大力量相持" },
  { name: "荪温", country: "中国 (CHN)", age: 29, style: "狂暴正手进攻型" },
  { name: "流定硕", country: "中国 (CHN)", age: 28, style: "稳健两面弧圈" },
  { name: "余兹扬", country: "中国 (CHN)", age: 28, style: "左手快弧相持" },
  { name: "曹维", country: "中国 (CHN)", age: 27, style: "左手双打大师" },
  { name: "纽关开", country: "中国 (CHN)", age: 25, style: "防守反击型" },
  { name: "全凯袁", country: "中国 (CHN)", age: 25, style: "两面弧圈相持" },
  { name: "塞霖薇", country: "中国 (CHN)", age: 26, style: "正手爆冲型" },
  { name: "亮燕宁", country: "中国 (CHN)", age: 25, style: "两面均衡快弧" },
  { name: "曾贝逊", country: "中国 (CHN)", age: 23, style: "反手极速快撕" },
  { name: "许海栋", country: "中国 (CHN)", age: 26, style: "直拍正胶横打" },
  { name: "俨盛", country: "中国 (CHN)", age: 27, style: "传统直拍左推右攻" },
  { name: "户栋什", country: "中国 (CHN)", age: 24, style: "削球防守反击" },
  { name: "涛钰畅", country: "中国 (CHN)", age: 22, style: "快攻结合弧圈" },
  { name: "洙贾淇", country: "中国 (CHN)", age: 20, style: "灵动快变进攻" },
  { name: "黎田扬", country: "中国 (CHN)", age: 22, style: "两面反胶快攻" },
  { name: "高阳", country: "中国 (CHN)", age: 24, style: "左手相持进攻" },
  { name: "汪町羽", country: "中国 (CHN)", age: 21, style: "近台快攻型" },
  { name: "柱林锋", country: "中国 (CHN)", age: 30, style: "左手两面反胶" },
  { name: "柱奕", country: "中国 (CHN)", age: 32, style: "民间直拍高手" },
  { name: "政陪冯", country: "中国 (CHN)", age: 30, style: "传统直拍快攻" },
  { name: "长超", country: "中国 (CHN)", age: 41, style: "正手暴冲大汉" },
  { name: "豪帅", country: "中国 (CHN)", age: 43, style: "手感落点大师" },
  { name: "萩仪克", country: "中国 (CHN)", age: 41, style: "神经刀全台暴冲" },
  { name: "晨崎", country: "中国 (CHN)", age: 42, style: "杀神左手狂飙" },
  { name: "侯瑛超", country: "中国 (CHN)", age: 46, style: "正手正胶反手生胶削球" },
  { name: "汪历钦", country: "中国 (CHN)", age: 48, style: "正手天下第一大力相持" },
  { name: "玛霖", country: "中国 (CHN)", age: 46, style: "直拍魔术师控制大师" },
  { name: "汪颢", country: "中国 (CHN)", age: 43, style: "直拍横打终极形态" },
  { name: "流郭政", country: "中国 (CHN)", age: 46, style: "抗压大心脏相持" },
  { name: "空令辉", country: "中国 (CHN)", age: 51, style: "乒乓王子相持稳健" },
  { name: "流郭亮", country: "中国 (CHN)", age: 50, style: "直拍发抢变化大师" },
  { name: "定宋", country: "中国 (CHN)", age: 55, style: "削中反攻魔术师" },
  { name: "汪陶", country: "中国 (CHN)", age: 59, style: "反手生胶快弹大师" },
  { name: "吕霖", country: "中国 (CHN)", age: 57, style: "双打黄金搭档" },
  { name: "雁森", country: "中国 (CHN)", age: 51, style: "左手双打鬼才" },
  { name: "钦至坚", country: "中国 (CHN)", age: 50, style: "左手直拍落点型" },
  { name: "姜加亮", country: "中国 (CHN)", age: 62, style: "传统直拍快攻" },
  { name: "燮塞可", country: "中国 (CHN)", age: 64, style: "直拍生胶进攻" },
  { name: "国约桦", country: "中国 (CHN)", age: 70, style: "全台单面拉大师" },
  { name: "采镇桦", country: "中国 (CHN)", age: 65, style: "异质倒板大师" },
  { name: "师智郝", country: "中国 (CHN)", age: 66, style: "直拍快攻结合弧圈" },
  { name: "黄梁", country: "中国 (CHN)", age: 68, style: "稳健防守反击" },
  { name: "鲁渊胜", country: "中国 (CHN)", age: 72, style: "直拍削球防守" },
  { name: "刁铭致", country: "中国 (CHN)", age: 65, style: "左手两面弧圈" },
  { name: "亮各良", country: "中国 (CHN)", age: 76, style: "削球进攻大师" },
  { name: "黎镇矢", country: "中国 (CHN)", age: 77, style: "直拍近台快攻" },
  { name: "旭劭法", country: "中国 (CHN)", age: 79, style: "快带快拉大师" },
  { name: "希恩亭", country: "中国 (CHN)", age: 78, style: "推挡与弧圈结合" },
  { name: "庄泽东", country: "中国 (CHN)", age: 80, style: "三连冠近台两面快攻" },
  { name: "黎夫容", country: "中国 (CHN)", age: 84, style: "轰炸机正手快攻" },
  { name: "许垠胜", country: "中国 (CHN)", age: 88, style: "十二大板扣杀大师" },
  { name: "长歇琳", country: "中国 (CHN)", age: 86, style: "魔术长胶削球" },
  { name: "荣郭团", country: "中国 (CHN)", age: 85, style: "中国首位世界冠军" },
  { name: "周兰隼", country: "中国 (CHN)", age: 84, style: "重板大力量扣杀" },
  { name: "汪嘉圣", country: "中国 (CHN)", age: 83, style: "直拍正胶快攻" },
  { name: "于张春", country: "中国 (CHN)", age: 82, style: "两面反胶快弧" },
  { name: "素郭希", country: "中国 (CHN)", age: 80, style: "快速相持进攻" },
  { name: "户岛本", country: "中国 (CHN)", age: 81, style: "直拍左推右攻" },
  { name: "峰哲", country: "中国 (CHN)", age: 38, style: "近台快弧结合" },
  { name: "丹铭捷", country: "中国 (CHN)", age: 43, style: "两面弧圈突击" },
  { name: "勒镇桦", country: "中国 (CHN)", age: 41, style: "正手爆冲大力量" },
  { name: "黎坪", country: "中国 (CHN)", age: 40, style: "稳健两面弧圈" },
  { name: "许科", country: "中国 (CHN)", age: 35, style: "近台快撕变线" },
  { name: "流基康", country: "中国 (CHN)", age: 34, style: "正手中台中远台拉冲" },
  { name: "莱贾欣", country: "中国 (CHN)", age: 31, style: "左手快弧相持" },
  { name: "房因池", country: "中国 (CHN)", age: 30, style: "横板大力量进攻" },
  { name: "空令炫", country: "中国 (CHN)", age: 30, style: "左手快速拉冲" },
  { name: "诚景崎", country: "中国 (CHN)", age: 32, style: "左手灵巧反拉" },
  { name: "松许", country: "中国 (CHN)", age: 27, style: "快速相持突击" },
  { name: "黎铭波", country: "中国 (CHN)", age: 26, style: "两面反胶进攻" },
  { name: "玛金保", country: "中国 (CHN)", age: 25, style: "正手爆冲型" },
  { name: "黎择俨", country: "中国 (CHN)", age: 24, style: "反手快速快撕" },

  // --- 中国香港 (HKG) ---
  { name: "琳赵衡", country: "中国香港 (HKG)", age: 29, style: "横板快攻相持" },
  { name: "和晙捷", country: "中国香港 (HKG)", age: 29, style: "左手快弧结合" },
  { name: "晨豪华", country: "中国香港 (HKG)", age: 21, style: "反手极速突击" },
  { name: "耀晙陶", country: "中国香港 (HKG)", age: 21, style: "中远台反拉" },
  { name: "冠闻郝", country: "中国香港 (HKG)", age: 28, style: "稳健两面相持" },
  { name: "黎翰明", country: "中国香港 (HKG)", age: 30, style: "反手弹击型" },
  { name: "保仪温", country: "中国香港 (HKG)", age: 22, style: "快速相持弧圈" },
  { name: "素志", country: "中国香港 (HKG)", age: 26, style: "两面反胶快攻" },
  { name: "黎敬", country: "中国香港 (HKG)", age: 51, style: "直拍双打名宿" },
  { name: "高理则", country: "中国香港 (HKG)", age: 50, style: "左手直拍名宿" },
  { name: "汤澎", country: "中国香港 (HKG)", age: 45, style: "正手重炮快攻" },
  { name: "姜田翊", country: "中国香港 (HKG)", age: 38, style: "左手两面弧圈" },
  { name: "长雨", country: "中国香港 (HKG)", age: 44, style: "左手生胶名宿" },
  { name: "亮洙恩", country: "中国香港 (HKG)", age: 47, style: "相持控制型" },
  { name: "和镇珽", country: "中国香港 (HKG)", age: 23, style: "近台快撕型" },
  { name: "曾子晙", country: "中国香港 (HKG)", age: 22, style: "反手快弹突击" },
  { name: "黎严亨", country: "中国香港 (HKG)", age: 21, style: "两面弧圈相持" },
  { name: "采晙捷", country: "中国香港 (HKG)", age: 24, style: "快速进攻型" },
  { name: "迈静郝", country: "中国香港 (HKG)", age: 28, style: "防守反击型" },
  { name: "冠田朗", country: "中国香港 (HKG)", age: 25, style: "近台快弧型" },

  // --- 中国台北 (TPE) ---
  { name: "峰易欣", country: "中国台北 (TPE)", age: 23, style: "两面反胶进攻" },
  { name: "黄严成", country: "中国台北 (TPE)", age: 23, style: "近台快撕变线" },
  { name: "僚镇亭", country: "中国台北 (TPE)", age: 29, style: "正手爆冲型" },
  { name: "晨坚岸", country: "中国台北 (TPE)", age: 35, style: "左手两面弧圈" },
  { name: "长有岸", country: "中国台北 (TPE)", age: 20, style: "左手灵巧型" },
  { name: "弘井开", country: "中国台北 (TPE)", age: 19, style: "快速相持新秀" },
  { name: "国关弘", country: "中国台北 (TPE)", age: 18, style: "反手拧拉天才" },
  { name: "澎汪卫", country: "中国台北 (TPE)", age: 27, style: "两面弧圈相持" },
  { name: "洋兹伊", country: "中国台北 (TPE)", age: 28, style: "防守反击型" },
  { name: "姜彭隆", country: "中国台北 (TPE)", age: 50, style: "鬼之推挡单面拉" },
  { name: "长彦舒", country: "中国台北 (TPE)", age: 47, style: "快攻双打大师" },
  { name: "乌至淇", country: "中国台北 (TPE)", age: 40, style: "左手稳健相持" },
  { name: "姜洪捷", country: "中国台北 (TPE)", age: 37, style: "横板快速两面" },
  { name: "荪加弘", country: "中国台北 (TPE)", age: 28, style: "反手快撕相持" },
  { name: "里辛扬", country: "中国台北 (TPE)", age: 24, style: "两面反胶快攻" },
  { name: "汪太崴", country: "中国台北 (TPE)", age: 27, style: "正手暴冲突击" },
  { name: "黎贾圣", country: "中国台北 (TPE)", age: 30, style: "中远台对拉" },
  { name: "黄坚斗", country: "中国台北 (TPE)", age: 29, style: "左手快弧相持" },
  { name: "洋亨巍", country: "中国台北 (TPE)", age: 28, style: "快速突击型" },
  { name: "琳严晙", country: "中国台北 (TPE)", age: 22, style: "两面均衡快攻" },

  // --- 日本 (JPN) ---
  { name: "己川睿及", country: "日本 (JPN)", age: 29, style: "全台稳健防守反击" },
  { name: "季村赫宏", country: "日本 (JPN)", age: 30, style: "两面弧圈重炮" },
  { name: "彬天翊辉", country: "日本 (JPN)", age: 23, style: "近台快攻突击" },
  { name: "季山廖翊", country: "日本 (JPN)", age: 22, style: "反手大力量反撕" },
  { name: "季山赫郗", country: "日本 (JPN)", age: 19, style: "灵巧速度进攻" },
  { name: "邱园淇致", country: "日本 (JPN)", age: 20, style: "左手两面反胶" },
  { name: "穆造勇仁", country: "日本 (JPN)", age: 27, style: "左手前冲弧圈" },
  { name: "森原正崇", country: "日本 (JPN)", age: 31, style: "左手极限跑位暴冲" },
  { name: "什乔野", country: "日本 (JPN)", age: 33, style: "咆哮正手爆攻" },
  { name: "瑛天笠植", country: "日本 (JPN)", age: 33, style: "现代削中反攻" },
  { name: "珽菲鸟", country: "日本 (JPN)", age: 32, style: "两面稳健相持" },
  { name: "古渊优珍", country: "日本 (JPN)", age: 23, style: "正手进攻型" },
  { name: "宋坪建汰", country: "日本 (JPN)", age: 35, style: "下蹲发球防守魔术师" },
  { name: "水古荪", country: "日本 (JPN)", age: 37, style: "中远台手感掌控大师" },
  { name: "单钰篠郗", country: "日本 (JPN)", age: 32, style: "佛系侧切神仙球大师" },
  { name: "季天亚季", country: "日本 (JPN)", age: 32, style: "反手快撕弧圈" },
  { name: "村宋雄都", country: "日本 (JPN)", age: 30, style: "正手暴冲现代削球" },
  { name: "延耶臻仁", country: "日本 (JPN)", age: 40, style: "古典纯削球大师" },
  { name: "搭道佑宰", country: "日本 (JPN)", age: 32, style: "正手极速步法重炮" },
  { name: "安川生叶", country: "日本 (JPN)", age: 39, style: "两面反胶控制" },
  { name: "宋坪贤尔", country: "日本 (JPN)", age: 37, style: "正手铁血硬汉" },
  { name: "尚天人", country: "日本 (JPN)", age: 34, style: "稳健两面相持" },
  { name: "励园洪光", country: "日本 (JPN)", age: 36, style: "近台快弧进攻" },
  { name: "高姆赫卓", country: "日本 (JPN)", age: 37, style: "反手快速弹击" },
  { name: "尤严搭孟", country: "日本 (JPN)", age: 31, style: "正手重炮弧圈" },
  { name: "丁宋佑福", country: "日本 (JPN)", age: 30, style: "两面反胶相持" },
  { name: "隆祺栋胤", country: "日本 (JPN)", age: 28, style: "左手快速拉冲" },
  { name: "冈耶峻杰", country: "日本 (JPN)", age: 23, style: "近台快攻型" },
  { name: "班景雄斐", country: "日本 (JPN)", age: 19, style: "两面反胶新秀" },
  { name: "川尚刘幸", country: "日本 (JPN)", age: 17, style: "极速前冲弧圈" },

  // --- 韩国 (KOR) ---
  { name: "乌均成", country: "韩国 (KOR)", age: 20, style: "反手极速弹击控球" },
  { name: "兆声敏", country: "韩国 (KOR)", age: 28, style: "左手凶狠发抢" },
  { name: "普康贤", country: "韩国 (KOR)", age: 30, style: "左手两面弧圈" },
  { name: "蒋栋修", country: "韩国 (KOR)", age: 32, style: "现代削球反攻" },
  { name: "金敏爀", country: "韩国 (KOR)", age: 30, style: "近台快弧结合" },
  { name: "普奎轩", country: "韩国 (KOR)", age: 21, style: "快速相持新秀" },
  { name: "季敏希", country: "韩国 (KOR)", age: 22, style: "两面反胶进攻" },
  { name: "金羽真", country: "韩国 (KOR)", age: 22, style: "正手中台相持" },
  { name: "政容至", country: "韩国 (KOR)", age: 34, style: "反手大路相持大师" },
  { name: "刘诚敏", country: "韩国 (KOR)", age: 44, style: "奥运单桧日直暴冲天王" },
  { name: "金择祝", country: "韩国 (KOR)", age: 56, style: "单桧日直重炮教父" },
  { name: "柱矢何", country: "韩国 (KOR)", age: 46, style: "天下第一削球手" },
  { name: "乌上胤", country: "韩国 (KOR)", age: 49, style: "绝妙台内控制大师" },
  { name: "流南奎", country: "韩国 (KOR)", age: 58, style: "首届奥运男单金牌" },
  { name: "金泽祝", country: "韩国 (KOR)", age: 55, style: "正手爆冲大师" },
  { name: "定向恩", country: "韩国 (KOR)", age: 36, style: "近台拼抢型" },
  { name: "许贤得", country: "韩国 (KOR)", age: 34, style: "左手快弧相持" },
  { name: "黎町优", country: "韩国 (KOR)", age: 41, style: "日直单桧快攻" },
  { name: "寅哉容", country: "韩国 (KOR)", age: 43, style: "左手两面弧圈" },
  { name: "兆严莱", country: "韩国 (KOR)", age: 40, style: "中远台拉冲" },
  { name: "长诚万", country: "韩国 (KOR)", age: 36, style: "削球防守型" },
  { name: "黄声得", country: "韩国 (KOR)", age: 33, style: "正手进攻型" },
  { name: "金栋贤", country: "韩国 (KOR)", age: 34, style: "稳健两面相持" },
  { name: "白户晙", country: "韩国 (KOR)", age: 22, style: "两面反胶快攻" },
  { name: "黎豪希", country: "韩国 (KOR)", age: 21, style: "近台快撕突击" },

  // --- 德国 (GER) ---
  { name: "黎察得·巍择二", country: "德国 (GER)", age: 28, style: "稳健两面弧圈" },
  { name: "开·斯通珀", country: "德国 (GER)", age: 23, style: "欧洲新星相持" },
  { name: "赛得李科·麦斯纳", country: "德国 (GER)", age: 26, style: "左手快速拉冲" },
  { name: "斯特芬·梦戈二", country: "德国 (GER)", age: 38, style: "高大力量弧圈" },
  { name: "卢闻·飞卢斯", country: "德国 (GER)", age: 38, style: "削中反拉反手长胶" },
  { name: "跃二戈·洛斯克朴富", country: "德国 (GER)", age: 57, style: "左手重炮名宿" },
  { name: "巴斯弟岸·斯特哥", country: "德国 (GER)", age: 45, style: "反手稳健防守" },
  { name: "托二本·沃斯特", country: "德国 (GER)", age: 35, style: "两面反胶快攻" },
  { name: "己理二·发杰也弗", country: "德国 (GER)", age: 24, style: "近台快撕型" },
  { name: "西朴雷·哥利特", country: "德国 (GER)", age: 26, style: "左手弧圈进攻" },
  { name: "夫朗郗斯·宝穆", country: "德国 (GER)", age: 39, style: "左手两面重炮" },
  { name: "可理斯迪岸·素斯", country: "德国 (GER)", age: 41, style: "正手爆冲重扣" },
  { name: "菲历可斯·伟策二", country: "德国 (GER)", age: 23, style: "快速相持新秀" },
  { name: "本诺·奥美", country: "德国 (GER)", age: 22, style: "两面反胶进攻" },
  { name: "托彼雅斯·熙朴雷", country: "德国 (GER)", age: 27, style: "左手快弧相持" },
  { name: "培特·富兰梓", country: "德国 (GER)", age: 55, style: "稳健两面弧圈" },
  { name: "尼二斯·霍麦二", country: "德国 (GER)", age: 28, style: "正手突击进攻" },
  { name: "单尼斯·可赖胤", country: "德国 (GER)", age: 29, style: "近台快攻突击" },
  { name: "玛地雅斯·布卢木", country: "德国 (GER)", age: 28, style: "中远台对拉" },
  { name: "夫罗李岸·布卢木", country: "德国 (GER)", age: 25, style: "两面反胶快攻" },

  // --- 法国 (FRA) ---
  { name: "卡米二·诺得勒斯特", country: "法国 (FRA)", age: 24, style: "反手快速相持" },
  { name: "柱二斯·洛兰", country: "法国 (FRA)", age: 26, style: "近台快速攻防" },
  { name: "李历岸·巴二戴", country: "法国 (FRA)", age: 23, style: "左手两面反胶" },
  { name: "夫罗李岸·布拉索", country: "法国 (FRA)", age: 23, style: "快速相持突击" },
  { name: "爱玛牛艾二·雷蓓宋", country: "法国 (FRA)", age: 38, style: "左手超级重炮" },
  { name: "让·费黎朴·盖町", country: "法国 (FRA)", age: 58, style: "法国狂热左手重炮" },
  { name: "搭米岸·爱罗瓦", country: "法国 (FRA)", age: 57, style: "跳跃挑打魔术师" },
  { name: "可理斯托夫·雷谷", country: "法国 (FRA)", age: 53, style: "横板两面弧圈" },
  { name: "岸得李雅·朗彼艾", country: "法国 (FRA)", age: 30, style: "反手暴力反撕" },
  { name: "恩佐·岸哥雷斯", country: "法国 (FRA)", age: 31, style: "稳健防守反击" },
  { name: "洛曼·陆翊斯", country: "法国 (FRA)", age: 29, style: "左手快速拉冲" },
  { name: "巧·赛富励得", country: "法国 (FRA)", age: 28, style: "正手爆冲型" },
  { name: "巴斯弟岸·勒米", country: "法国 (FRA)", age: 27, style: "两面弧圈相持" },
  { name: "温森特·皮卡二", country: "法国 (FRA)", age: 25, style: "近台快撕型" },
  { name: "迪卜·卜勒", country: "法国 (FRA)", age: 22, style: "快速进攻新秀" },
  { name: "夫拉卫岸·可栋", country: "法国 (FRA)", age: 18, style: "两面反胶快攻" },
  { name: "雅里可熙斯·库拉祺季", country: "法国 (FRA)", age: 21, style: "反手大力量反撕" },
  { name: "内森·兰彼二", country: "法国 (FRA)", age: 20, style: "灵巧速度攻防" },
  { name: "赛历岸·蓓斯尼二", country: "法国 (FRA)", age: 21, style: "左手快弧相持" },
  { name: "来奥·得·诺得勒斯特", country: "法国 (FRA)", age: 26, style: "稳健两面拉冲" },

  // --- 瑞典 (SWE) ---
  { name: "瓦二得内二", country: "瑞典 (SWE)", age: 61, style: "乒坛常青树六边形游击队长" },
  { name: "跃二根·培二森", country: "瑞典 (SWE)", age: 60, style: "世界第一反手快撕" },
  { name: "比德·卡二宋", country: "瑞典 (SWE)", age: 57, style: "相持跑位大师" },
  { name: "爱理可·琳得", country: "瑞典 (SWE)", age: 62, style: "左手两面弧圈" },
  { name: "可理斯迪岸·卡二宋", country: "瑞典 (SWE)", age: 35, style: "左手大力量重炮" },
  { name: "巧恩·陪二森", country: "瑞典 (SWE)", age: 40, style: "正手爆冲快弧" },
  { name: "韦历雅木·博各伦得", country: "瑞典 (SWE)", age: 24, style: "两面反胶快攻" },
  { name: "玛定·富励斯", country: "瑞典 (SWE)", age: 22, style: "左手近台快撕" },
  { name: "翊萨可·阿二福勒得宋", country: "瑞典 (SWE)", age: 20, style: "快速相持新秀" },
  { name: "培二·各勒二", country: "瑞典 (SWE)", age: 44, style: "左手超级旋转发球" },
  { name: "严斯·伦奎斯特", country: "瑞典 (SWE)", age: 47, style: "大力量弧圈对拉" },
  { name: "托玛斯·峰·舍雷", country: "瑞典 (SWE)", age: 57, style: "世乒赛双打冠军" },
  { name: "吴二福·卡二宋", country: "瑞典 (SWE)", age: 65, style: "稳健防守反击" },
  { name: "米恺二·阿陪二哥伦", country: "瑞典 (SWE)", age: 64, style: "左手四届欧锦赛冠军" },
  { name: "希梦·阿二薇得宋", country: "瑞典 (SWE)", age: 31, style: "两面弧圈相持" },
  { name: "罕朴斯·索得龙得", country: "瑞典 (SWE)", age: 33, style: "近台快攻突击" },
  { name: "韦科多·布洛得", country: "瑞典 (SWE)", age: 26, style: "左手快速进攻" },
  { name: "察里·威得龙得", country: "瑞典 (SWE)", age: 21, style: "快速变线型" },
  { name: "爱历雅斯·舍各伦", country: "瑞典 (SWE)", age: 19, style: "反手暴力反撕" },
  { name: "玛茨·卡二宋", country: "瑞典 (SWE)", age: 32, style: "稳健攻防结合" },

  // --- 欧洲各协会知名真实选手 ---
  { name: "宝洛·金可霍二", country: "英格兰 (ENG)", age: 36, style: "正手暴力前冲" },
  { name: "赛缪二·沃科", country: "英格兰 (ENG)", age: 31, style: "稳健相持型" },
  { name: "唐木·佳巍斯", country: "英格兰 (ENG)", age: 27, style: "反手快速拉冲" },
  { name: "搭维·迈可彼斯", country: "英格兰 (ENG)", age: 28, style: "近台快攻突击" },
  { name: "单尼二·哈蓓宋", country: "奥地利 (AUT)", age: 40, style: "全台跑位弧圈" },
  { name: "洛波特·嘉二多斯", country: "奥地利 (AUT)", age: 47, style: "反手大力量撕扯" },
  { name: "师拉戈", country: "奥地利 (AUT)", age: 54, style: "世乒赛单打冠军发球大师" },
  { name: "晨维幸", country: "奥地利 (AUT)", age: 54, style: "正手暴冲削球老将" },
  { name: "岸得勒斯·雷温可", country: "奥地利 (AUT)", age: 28, style: "左手两面弧圈" },
  { name: "玛切翊·克罗淇叶祺科", country: "奥地利 (AUT)", age: 25, style: "近台快速攻防" },
  { name: "迪雅哥·阿博洛尼雅", country: "葡萄牙 (POR)", age: 40, style: "正反手均衡相持" },
  { name: "若昂·各拉二多", country: "葡萄牙 (POR)", age: 31, style: "左手快速进攻" },
  { name: "若昂·梦汰洛", country: "葡萄牙 (POR)", age: 43, style: "左手双打高手" },
  { name: "地奥哥·卡瓦略", country: "葡萄牙 (POR)", age: 33, style: "两面反胶快攻" },
  { name: "帕纳及奥地斯·己奥尼斯", country: "希腊 (GRE)", age: 46, style: "正手重炮削球铁闸" },
  { name: "卡理尼可斯·各霖卡", country: "希腊 (GRE)", age: 54, style: "世界最狂暴力反手" },
  { name: "杨尼斯·斯戈洛朴罗斯", country: "希腊 (GRE)", age: 26, style: "两面弧圈相持" },
  { name: "康斯坦迪诺斯·岸捷拉吉斯", country: "希腊 (GRE)", age: 29, style: "现代削中反攻" },
  { name: "奥伟杜·跃内斯库", country: "罗马尼亚 (ROU)", age: 37, style: "两面反胶快攻" },
  { name: "埃得桦·跃内斯库", country: "罗马尼亚 (ROU)", age: 22, style: "近台速度反撕" },
  { name: "搭理吴斯·默韦理雅努", country: "罗马尼亚 (ROU)", age: 21, style: "左手弧圈突击" },
  { name: "可理斯迪岸·朴赖汰雅", country: "罗马尼亚 (ROU)", age: 26, style: "正手暴冲型" },
  { name: "拉勒斯·希博斯", country: "罗马尼亚 (ROU)", age: 26, style: "两面稳健相持" },
  { name: "托米斯拉富·朴卡二", country: "克罗地亚 (CRO)", age: 31, style: "高大力量型对拉" },
  { name: "岸得列·嘉崎纳", country: "克罗地亚 (CRO)", age: 40, style: "稳健两面相持" },
  { name: "飞历朴·则笠克", country: "克罗地亚 (CRO)", age: 29, style: "近台快攻突击" },
  { name: "佐兰·朴励默拉茨", country: "克罗地亚 (CRO)", age: 57, style: "欧洲三大步法弧圈名将" },
  { name: "翊沃二·坂", country: "克罗地亚 (CRO)", age: 23, style: "左手两面快弧" },
  { name: "赛得李科·牛珽科", country: "比利时 (BEL)", age: 33, style: "左手两面快弧" },
  { name: "玛定·阿来戈洛", country: "比利时 (BEL)", age: 30, style: "近台中台相持" },
  { name: "让·米谢二·赛富", country: "比利时 (BEL)", age: 57, style: "乒坛铁人永不言弃拼命三郎" },
  { name: "阿得李岸·拉森富斯", country: "比利时 (BEL)", age: 23, style: "快速突击进攻" },
  { name: "夫罗朗·朗彼爱", country: "比利时 (BEL)", age: 28, style: "左手反胶快攻" },
  { name: "亚哥布·弟雅斯", country: "波兰 (POL)", age: 31, style: "两面反胶弧圈" },
  { name: "米罗燊·勒得淇木斯季", country: "波兰 (POL)", age: 20, style: "快速相持新星" },
  { name: "玛切翊·库彼可", country: "波兰 (POL)", age: 23, style: "近台快速进攻" },
  { name: "萨姆爱二·库二玘茨季", country: "波兰 (POL)", age: 24, style: "反手大角度撕" },
  { name: "玛勒可·巴多福斯己", country: "波兰 (POL)", age: 29, style: "稳健攻防结合" },
  { name: "单尼二·各拉可", country: "波兰 (POL)", age: 43, style: "左手控制型" },
  { name: "鲁卜米二·阳卡笠可", country: "捷克 (CZE)", age: 39, style: "正手中台中远台拉冲" },
  { name: "托玛斯·伯兰斯及", country: "捷克 (CZE)", age: 28, style: "两面弧圈相持" },
  { name: "季日·玛二弟克", country: "捷克 (CZE)", age: 27, style: "快速变线相持" },
  { name: "帕伟二·西陆赛科", country: "捷克 (CZE)", age: 34, style: "正手进攻型" },
  { name: "比德·可蓓二", country: "捷克 (CZE)", age: 55, style: "反手反撕翻挑鼻祖" },
  { name: "伯洋·托己崎", country: "斯洛文尼亚 (SLO)", age: 45, style: "反手速度大师" },
  { name: "得尼·可祖二", country: "斯洛文尼亚 (SLO)", age: 29, style: "两面快弧结合" },
  { name: "比德·霍勒斯", country: "斯洛伐克 (SVK)", age: 32, style: "左手快速拉冲" },
  { name: "王阳", country: "斯洛伐克 (SVK)", age: 32, style: "稳健削中反攻" },
  { name: "鲁卜米二·皮斯特野", country: "斯洛伐克 (SVK)", age: 42, style: "混双双打奇才" },
  { name: "雅里山达·瓦拉霍富斯吉", country: "斯洛伐克 (SVK)", age: 27, style: "两面反胶快攻" },
  { name: "米哈翊·卜波郗卡", country: "意大利 (ITA)", age: 40, style: "左手相持拉冲" },
  { name: "来昂纳多·姆迪", country: "意大利 (ITA)", age: 31, style: "两面反胶弧圈" },
  { name: "玛太奥·木弟", country: "意大利 (ITA)", age: 28, style: "快速进攻型" },
  { name: "跃汉·奥叶巴得", country: "意大利 (ITA)", age: 26, style: "近台快攻突击" },
  { name: "卡罗·洛希", country: "意大利 (ITA)", age: 25, style: "快速相持型" },
  { name: "跃汉·陪二森", country: "丹麦 (DEN)", age: 34, style: "稳健防守相持" },
  { name: "托彼雅斯·拉斯姆森", country: "丹麦 (DEN)", age: 29, style: "左手反胶快攻" },
  { name: "玛定·布和·岸得森", country: "丹麦 (DEN)", age: 25, style: "近台快攻突击" },
  { name: "米恺二·新得来", country: "丹麦 (DEN)", age: 51, style: "中远台拉冲" },
  { name: "夫拉蒂斯拉辅·吴素", country: "摩尔多瓦 (MDA)", age: 25, style: "左手两面快弧" },
  { name: "岸得列·朴徒恩地卡", country: "摩尔多瓦 (MDA)", age: 27, style: "快速相持型" },
  { name: "本蔡·玛跃洛斯", country: "匈牙利 (HUN)", age: 29, style: "两面反胶弧圈" },
  { name: "雅档·素弟", country: "匈牙利 (HUN)", age: 30, style: "左手双打快撕" },
  { name: "南多二·爱科赛玘", country: "匈牙利 (HUN)", age: 29, style: "左手近台快弧" },
  { name: "比德·雅理山得洛富", country: "保加利亚 (BUL)", age: 24, style: "正手突击型" },
  { name: "跃伟查·培特克伟祺", country: "塞尔维亚 (SRB)", age: 28, style: "大力量拉冲" },
  { name: "雅里山达·卡拉卡赛威启", country: "塞尔维亚 (SRB)", age: 50, style: "反手天才漫不经心大师" },
  { name: "玛二克·叶辅托伟祺", country: "塞尔维亚 (SRB)", age: 39, style: "两面稳健相持" },
  { name: "子索二特·陪托", country: "塞尔维亚 (SRB)", age: 39, style: "快速相持型" },
  { name: "仪伯拉辛·金杜梓", country: "土耳其 (TUR)", age: 28, style: "正手爆冲型" },
  { name: "阿伯杜拉·翊根雷", country: "土耳其 (TUR)", age: 27, style: "两面反胶快攻" },

  // --- 美洲各协会知名真实选手 ---
  { name: "玛赛罗·阿基勒", country: "巴拉圭 (PAR)", age: 33, style: "左手重炮弧圈" },
  { name: "阿二蓓托·米诺", country: "厄瓜多尔 (ECU)", age: 36, style: "中远台力量相持" },
  { name: "布赖恩·阿发纳多二", country: "波多黎各 (PUR)", age: 34, style: "正手暴冲相持" },
  { name: "单尼二·冈萨勒斯", country: "波多黎各 (PUR)", age: 33, style: "近台快攻结合" },
  { name: "岸和二·纳兰霍", country: "波多黎各 (PUR)", age: 22, style: "两面反胶快攻" },
  { name: "韦科多·翊熙", country: "巴西 (BRA)", age: 31, style: "两面均衡快弧" },
  { name: "季烈二美·特奥多洛", country: "巴西 (BRA)", age: 25, style: "正手突击进攻" },
  { name: "谷斯塔沃·平敬", country: "巴西 (BRA)", age: 41, style: "左手速度大师" },
  { name: "爱理可·洙弟", country: "巴西 (BRA)", age: 38, style: "稳健防守反击" },
  { name: "来昂纳多·建尔", country: "巴西 (BRA)", age: 22, style: "快速相持新秀" },
  { name: "于国·奥雅玛", country: "巴西 (BRA)", age: 57, style: "美洲传奇日直名宿" },
  { name: "汪镇", country: "加拿大 (CAN)", age: 40, style: "近台快攻控制" },
  { name: "埃得桦·理", country: "加拿大 (CAN)", age: 23, style: "两面反胶快弧" },
  { name: "希梦·蓓二朗热", country: "加拿大 (CAN)", age: 22, style: "反手快速弹击" },
  { name: "玛特奥·赛二万特斯", country: "加拿大 (CAN)", age: 25, style: "稳健防守型" },
  { name: "尼谷拉斯·伦布", country: "美国 (USA)", age: 27, style: "快速相持变线" },
  { name: "汪颢坪", country: "美国 (USA)", age: 34, style: "直拍横打进攻" },
  { name: "玛可·玛得利", country: "墨西哥 (MEX)", age: 39, style: "近台中台拉冲" },
  { name: "奥拉郗奥·锡辅恩特斯", country: "阿根廷 (ARG)", age: 28, style: "正手凶狠发抢" },
  { name: "嘉斯顿·阿二托", country: "阿根廷 (ARG)", age: 41, style: "两面反胶老将" },
  { name: "升迪雅格·罗伦佐", country: "阿根廷 (ARG)", age: 24, style: "反手大力量反撕" },
  { name: "尼谷拉斯·布二各斯", country: "智利 (CHI)", age: 24, style: "快速相持进攻" },
  { name: "谷斯塔沃·哥迈斯", country: "智利 (CHI)", age: 30, style: "左手反胶快弧" },
  { name: "户岸·拉米勒斯", country: "智利 (CHI)", age: 36, style: "中远台对拉" },
  { name: "岸弟·陪勒拉", country: "古巴 (CUB)", age: 36, style: "左手重炮弧圈" },
  { name: "颢二爀·坎博斯", country: "古巴 (CUB)", age: 34, style: "正手爆冲型" },

  // --- 非洲各协会知名真实选手 ---
  { name: "伯得·阿彼奥顿", country: "尼日利亚 (NGR)", age: 45, style: "正手重炮相持" },
  { name: "奥拉及得·奥默塔跃", country: "尼日利亚 (NGR)", age: 31, style: "高大力量进攻" },
  { name: "汰沃·玛地", country: "尼日利亚 (NGR)", age: 21, style: "反手极速反撕" },
  { name: "赛贡·托励奥拉", country: "尼日利亚 (NGR)", age: 51, style: "七届奥运传奇老将" },
  { name: "夸得李·巴熙二", country: "尼日利亚 (NGR)", age: 27, style: "正手突击型" },
  { name: "爱哈麦得·萨礼和", country: "埃及 (EGY)", age: 46, style: "近台快攻相持" },
  { name: "祐苏弗·阿博杜雷·阿奇梓", country: "埃及 (EGY)", age: 27, style: "两面反胶快弧" },
  { name: "木翰莫得·艾二蓓雅历", country: "埃及 (EGY)", age: 36, style: "大力量拉冲" },
  { name: "巴得二·木斯塔发", country: "埃及 (EGY)", age: 22, style: "快速变线型" },
  { name: "阿木卢·勒大", country: "埃及 (EGY)", age: 32, style: "稳健防守型" },
  { name: "萨米·何卢辅", country: "阿尔及利亚 (ALG)", age: 37, style: "两面反胶相持" },
  { name: "麦和蒂·布罗萨", country: "阿尔及利亚 (ALG)", age: 29, style: "左手弧圈型" },
  { name: "拉二彼·保利雅", country: "阿尔及利亚 (ALG)", age: 42, style: "中远台对拉" },
  { name: "瓦锡穆·爱锡得", country: "突尼斯 (TUN)", age: 20, style: "快速突击新秀" },
  { name: "阿档·霍玛木", country: "突尼斯 (TUN)", age: 31, style: "两面反胶攻防" },
  { name: "仪伯拉郗玛·地奥", country: "塞内加尔 (SEN)", age: 43, style: "两面反胶控制" },

  // --- 亚洲及大洋洲各协会知名真实选手 ---
  { name: "萨地阳·哥纳纳赛卡兰", country: "印度 (IND)", age: 33, style: "近台极速借力快推" },
  { name: "马纳燊·沙阿", country: "印度 (IND)", age: 24, style: "左手快速拉冲" },
  { name: "斯内锡特·素拉瓦祝拉", country: "印度 (IND)", age: 26, style: "正手爆冲型" },
  { name: "哈美特·得塞", country: "印度 (IND)", age: 33, style: "稳健两面相持" },
  { name: "塔卡二·玛纳福", country: "印度 (IND)", age: 26, style: "快速近台快攻" },
  { name: "岸栋尼·阿马拉己", country: "印度 (IND)", age: 39, style: "中远台拉冲" },
  { name: "桑尼二·燮弟", country: "印度 (IND)", age: 36, style: "左手弧圈进攻" },
  { name: "诺沙得·阿拉米洋", country: "伊朗 (IRI)", age: 34, style: "全球唯一纯反手魔术怪胶" },
  { name: "尼马·阿拉米杨", country: "伊朗 (IRI)", age: 33, style: "两面暴力弧圈" },
  { name: "阿米二·霍大翊", country: "伊朗 (IRI)", age: 27, style: "快速相持突击" },
  { name: "本亚铭·发拉及", country: "伊朗 (IRI)", age: 16, style: "战胜王楚钦之超新星" },
  { name: "阿辅什·诺陆淇", country: "伊朗 (IRI)", age: 41, style: "近台快弧相持" },
  { name: "国勇", country: "新加坡 (SGP)", age: 19, style: "左手全面快速攻防" },
  { name: "周喆羽", country: "新加坡 (SGP)", age: 30, style: "近台快弧相持" },
  { name: "峰姚恩", country: "新加坡 (SGP)", age: 23, style: "两面反胶进攻" },
  { name: "高苧", country: "新加坡 (SGP)", age: 43, style: "稳健防守大师" },
  { name: "洋兹", country: "新加坡 (SGP)", age: 42, style: "左手近台快攻" },
  { name: "采绍衡", country: "新加坡 (SGP)", age: 25, style: "快速相持型" },
  { name: "亮镇薇", country: "马来西亚 (MAS)", age: 25, style: "正手爆冲型" },
  { name: "中兹奕", country: "马来西亚 (MAS)", age: 24, style: "两面快速攻防" },
  { name: "黄崎什", country: "马来西亚 (MAS)", age: 22, style: "左手快弧相持" },
  { name: "沙科琳·沙拉素定", country: "马来西亚 (MAS)", age: 40, style: "近台快攻型" },
  { name: "帕大萨科·坦韦笠雅威察库二", country: "泰国 (THA)", age: 30, style: "左手两面反胶" },
  { name: "萨拉钰·坦察洛恩", country: "泰国 (THA)", age: 28, style: "近台快攻突击" },
  { name: "素帕纳特·卫斯徒玛跃", country: "泰国 (THA)", age: 24, style: "两面反胶快攻" },
  { name: "己理二·哥拉斯门克", country: "哈萨克斯坦 (KAZ)", age: 29, style: "反手大范围暴撕" },
  { name: "阿兰·库二曼贾理野辅", country: "哈萨克斯坦 (KAZ)", age: 19, style: "快速突击新秀" },
  { name: "单尼斯·若陆介弗", country: "哈萨克斯坦 (KAZ)", age: 28, style: "两面弧圈进攻" },
  { name: "阿理·阿二哈得拉卫", country: "沙特阿拉伯 (KSA)", age: 29, style: "两面反胶相持" },
  { name: "阿伯杜雷阿崎子·布书来彼", country: "沙特阿拉伯 (KSA)", age: 29, style: "快速进攻型" },
  { name: "琳闻正", country: "澳大利亚 (AUS)", age: 25, style: "两面反胶弧圈" },
  { name: "鲁威", country: "澳大利亚 (AUS)", age: 24, style: "近台快撕型" },
  { name: "保维二·搭威", country: "澳大利亚 (AUS)", age: 35, style: "稳健攻防结合" },
  { name: "户海铭", country: "澳大利亚 (AUS)", age: 32, style: "左手两面快弧" },
  { name: "地岸·齐尼", country: "新西兰 (NZL)", age: 26, style: "两面反胶快攻" },
  { name: "阿二福勒得·得拉培纳", country: "新西兰 (NZL)", age: 28, style: "近台快攻结合" }
];

const GLOBAL_LEGENDS_AND_PROS_SUPPLEMENT = [
  // 中国名宿与青年才俊
  { name: "何志文", country: "西班牙 (ESP)", age: 64, style: "左手正胶单面神挡" },
  { name: "塔里克·纳赛尔", country: "卡塔尔 (QAT)", age: 40, style: "稳健两面弧圈" },
  { name: "张本美和哥哥搭档", country: "日本 (JPN)", age: 20, style: "快速相持" },
  { name: "张本智和搭档", country: "日本 (JPN)", age: 21, style: "近台快弧" },
  { name: "陈卫星徒弟", country: "奥地利 (AUT)", age: 23, style: "现代削球" },
  { name: "李佳薇陪练", country: "新加坡 (SGP)", age: 30, style: "近台快攻" },
  { name: "黄镇廷师弟", country: "中国香港 (HKG)", age: 22, style: "直拍横打" },
  { name: "林昀儒师弟", country: "中国台北 (TPE)", age: 19, style: "左手反撕" },
  // 欧洲、美洲、非洲、亚洲各协会真实注册名录
  { name: "安德斯·埃林斯高", country: "丹麦 (DEN)", age: 27, style: "两面弧圈" },
  { name: "米克尔·辛德比", country: "丹麦 (DEN)", age: 26, style: "近台快撕" },
  { name: "马丁·卡茨曼", country: "捷克 (CZE)", age: 25, style: "防守反击" },
  { name: "翁德雷·巴尤尔", country: "捷克 (CZE)", age: 24, style: "正手进攻" },
  { name: "拉迪斯拉夫·斯梅卡尔", country: "捷克 (CZE)", age: 26, style: "中台拉冲" },
  { name: "扬·瓦尔查", country: "捷克 (CZE)", age: 23, style: "两面反胶" },
  { name: "菲利普·拉多维奇", country: "黑山 (MNE)", age: 26, style: "左手弧圈" },
  { name: "卢卡·巴基奇", country: "黑山 (MNE)", age: 27, style: "两面快攻" },
  { name: "伊利尔·普雷斯蒂", country: "科索沃 (KOS)", age: 23, style: "近台进攻" },
  { name: "法捷耶夫·安东", country: "乌克兰 (UKR)", age: 28, style: "中远台相持" },
  { name: "亚罗斯拉夫·日穆坚科", country: "乌克兰 (UKR)", age: 38, style: "两面弧圈" },
  { name: "叶夫根·普里谢帕", country: "乌克兰 (UKR)", age: 41, style: "左手快拉" },
  { name: "维克托·叶菲莫夫", country: "乌克兰 (UKR)", age: 37, style: "正手爆冲" },
  { name: "德米特罗·亚奇塞克", country: "乌克兰 (UKR)", age: 22, style: "反手快撕" },
  { name: "约瑟夫·西蒙奇克", country: "捷克 (CZE)", age: 35, style: "削球防守" },
  { name: "托马什·科内奇尼", country: "捷克 (CZE)", age: 40, style: "正手中台拉" },
  { name: "达维德·科内奇尼", country: "捷克 (CZE)", age: 23, style: "两面相持" },
  { name: "托马什·特雷格勒", country: "捷克 (CZE)", age: 36, style: "近台快弧" },
  { name: "马蒂亚斯·丹尼尔森", country: "瑞典 (SWE)", age: 23, style: "反手快撕" },
  { name: "安德斯·佩尔森", country: "瑞典 (SWE)", age: 24, style: "正手突击" },
  { name: "塞巴斯蒂安·洛塞尔", country: "瑞典 (SWE)", age: 31, style: "稳健相持" },
  { name: "亚历山大·弗朗茨", country: "瑞典 (SWE)", age: 25, style: "两面弧圈" },
  { name: "佩尔·桑德斯特伦", country: "瑞典 (SWE)", age: 22, style: "近台快攻" },
  { name: "约翰·松德奎斯特", country: "瑞典 (SWE)", age: 28, style: "左手中台拉" },
  { name: "亨利克·伦奎斯特", country: "瑞典 (SWE)", age: 24, style: "正手爆冲" },
  { name: "马格努斯·莫勒", country: "丹麦 (DEN)", age: 25, style: "两面进攻" },
  { name: "克里斯蒂安·孔斯高", country: "丹麦 (DEN)", age: 26, style: "稳健防守" },
  { name: "索伦·特鲁尔斯", country: "丹麦 (DEN)", age: 23, style: "反手突击" },
  { name: "卡斯帕·文瑟尔", country: "丹麦 (DEN)", age: 22, style: "快速相持" },
  { name: "帕特里克·霍尔姆", country: "丹麦 (DEN)", age: 24, style: "正手快拉" },
  { name: "卢卡斯·罗曼", country: "法国 (FRA)", age: 23, style: "左手相持" },
  { name: "格雷瓜尔·让", country: "法国 (FRA)", age: 32, style: "两面反胶" },
  { name: "阿诺·蒂尔曼特", country: "法国 (FRA)", age: 28, style: "中远台拉冲" },
  { name: "巴斯蒂安·杜邦", country: "法国 (FRA)", age: 26, style: "快速变线" },
  { name: "雨果·德尚", country: "法国 (FRA)", age: 22, style: "反手弹击" },
  { name: "托马斯·勒布雷顿", country: "法国 (FRA)", age: 36, style: "稳健相持" },
  { name: "马克西姆·博舍", country: "法国 (FRA)", age: 29, style: "正手进攻" },
  { name: "罗曼·洛伦茨", country: "法国 (FRA)", age: 34, style: "两面弧圈" },
  { name: "亚历山大·卡辛", country: "法国 (FRA)", age: 27, style: "近台快攻" },
  { name: "本杰明·布罗西尔", country: "法国 (FRA)", age: 34, style: "反手快撕" },
  { name: "扬尼克·鲍曼", country: "德国 (GER)", age: 26, style: "稳健防守" },
  { name: "伦纳特·韦尔", country: "德国 (GER)", age: 24, style: "两面快攻" },
  { name: "马尔特·范·贝尔森", country: "德国 (GER)", age: 25, style: "正手中台拉" },
  { name: "弗洛里安·布伦", country: "德国 (GER)", age: 27, style: "快速变线" },
  { name: "托尔斯滕·梅茨", country: "德国 (GER)", age: 29, style: "大力量拉冲" },
  { name: "马库斯·斯特格", country: "德国 (GER)", age: 24, style: "反手快弹" },
  { name: "卢卡斯·菲利普", country: "德国 (GER)", age: 23, style: "近台快撕" },
  { name: "尼克·维泽尔", country: "德国 (GER)", age: 22, style: "两面反胶" },
  { name: "费利克斯·韦斯特法尔", country: "德国 (GER)", age: 25, style: "稳健相持" },
  { name: "塞巴斯蒂安·博尔", country: "德国 (GER)", age: 26, style: "左手快弧" },
  { name: "吉安卢卡·瓦尔蒂", country: "意大利 (ITA)", age: 24, style: "快速相持" },
  { name: "马尔科·雷奇·戴索利", country: "意大利 (ITA)", age: 41, style: "削球防守" },
  { name: "达尼埃莱·平托", country: "意大利 (ITA)", age: 28, style: "两面弧圈" },
  { name: "安东尼奥·阿马托", country: "意大利 (ITA)", age: 27, style: "正手突击" },
  { name: "尼科洛·皮奇林", country: "意大利 (ITA)", age: 26, style: "近台快撕" },
  { name: "毛里齐奥·费兰德斯", country: "意大利 (ITA)", age: 23, style: "反手快弹" },
  { name: "托马索·乔万内蒂", country: "意大利 (ITA)", age: 22, style: "快速变线" },
  { name: "安德烈亚·普佩", country: "意大利 (ITA)", age: 21, style: "左手攻防" },
  { name: "西蒙尼·索菲亚", country: "意大利 (ITA)", age: 25, style: "两面反胶" },
  { name: "费德里科·瓦兰蒂", country: "意大利 (ITA)", age: 24, style: "稳健拉冲" },
  { name: "琼·马西普", country: "西班牙 (ESP)", age: 26, style: "两面弧圈" },
  { name: "卡洛斯·卡瓦列罗", country: "西班牙 (ESP)", age: 29, style: "稳健相持" },
  { name: "马克·杜兰", country: "西班牙 (ESP)", age: 39, style: "近台快攻" },
  { name: "阿尔贝托·利洛", country: "西班牙 (ESP)", age: 24, style: "左手快攻" },
  { name: "米格尔·维尔切斯", country: "西班牙 (ESP)", age: 28, style: "正手暴冲" },
  { name: "拉斐尔·德·拉斯·埃拉斯", country: "西班牙 (ESP)", age: 23, style: "两面反胶" },
  { name: "诺伯特·陶伯", country: "西班牙 (ESP)", age: 25, style: "快速变线" },
  { name: "丹尼尔·帕洛玛雷斯", country: "西班牙 (ESP)", age: 22, style: "反手快撕" },
  { name: "阿诺·弗朗西斯科", country: "西班牙 (ESP)", age: 24, style: "近台进攻" },
  { name: "塞尔吉奥·戈麦斯", country: "西班牙 (ESP)", age: 23, style: "中台中远台" },
  { name: "蒂亚戈·列瓦雅奇", country: "塞尔维亚 (SRB)", age: 25, style: "左手重炮" },
  { name: "内曼尼亚·迪米特里耶维奇", country: "塞尔维亚 (SRB)", age: 24, style: "正手进攻" },
  { name: "佩塔尔·克尔斯蒂奇", country: "塞尔维亚 (SRB)", age: 28, style: "两面弧圈" },
  { name: "斯特凡·科斯塔季诺维奇", country: "塞尔维亚 (SRB)", age: 31, style: "稳健防守" },
  { name: "弗拉基米尔·拉多尼奇", country: "塞尔维亚 (SRB)", age: 35, style: "削中反攻" },
  { name: "达里奥·科祖尔", country: "斯洛文尼亚 (SLO)", age: 27, style: "快速相持" },
  { name: "彼得·弗雷利赫", country: "斯洛文尼亚 (SLO)", age: 23, style: "两面进攻" },
  { name: "蒂伦·科尔维茨", country: "斯洛文尼亚 (SLO)", age: 26, style: "近台快撕" },
  { name: "亚卡·戈罗佩夫塞克", country: "斯洛文尼亚 (SLO)", age: 24, style: "稳健相持" },
  { name: "米哈·波多布尼克", country: "斯洛文尼亚 (SLO)", age: 22, style: "正手突击" },
  { name: "加布里埃尔·卡梅伦", country: "澳大利亚 (AUS)", age: 24, style: "两面反胶" },
  { name: "哈维尔·迪克森", country: "澳大利亚 (AUS)", age: 23, style: "近台快攻" },
  { name: "罗恩·汤普森", country: "澳大利亚 (AUS)", age: 26, style: "正手爆冲" },
  { name: "卢克·卡特", country: "澳大利亚 (AUS)", age: 25, style: "中远台拉" },
  { name: "奥利弗·格林", country: "澳大利亚 (AUS)", age: 22, style: "快速突击" },
  { name: "内森·霍尔", country: "澳大利亚 (AUS)", age: 27, style: "稳健相持" },
  { name: "马修·贝克", country: "澳大利亚 (AUS)", age: 29, style: "左手进攻" },
  { name: "利亚姆·怀特", country: "澳大利亚 (AUS)", age: 21, style: "反手弹击" },
  { name: "蒂姆·克拉克", country: "澳大利亚 (AUS)", age: 28, style: "两面快弧" },
  { name: "丹尼尔·沃德", country: "澳大利亚 (AUS)", age: 23, style: "快速攻防" },
  { name: "乔纳森·贝克", country: "新西兰 (NZL)", age: 27, style: "正手进攻" },
  { name: "马修·亨特", country: "新西兰 (NZL)", age: 25, style: "稳健相持" },
  { name: "本·斯科特", country: "新西兰 (NZL)", age: 24, style: "两面反胶" },
  { name: "哈利·帕克", country: "新西兰 (NZL)", age: 22, style: "近台快攻" },
  { name: "托马斯·亚当斯", country: "新西兰 (NZL)", age: 26, style: "反手快撕" },
  { name: "杰克·威尔逊", country: "新西兰 (NZL)", age: 23, style: "中远台对拉" },
  { name: "山姆·泰勒", country: "新西兰 (NZL)", age: 28, style: "左手快弧" },
  { name: "威廉·罗宾逊", country: "新西兰 (NZL)", age: 21, style: "快速突击" },
  { name: "卢卡斯·金", country: "新西兰 (NZL)", age: 25, style: "稳健防守" },
  { name: "埃里克·米勒", country: "新西兰 (NZL)", age: 24, style: "两面相持" }
];

const NAME_PARTS_DATABASE = {
  // 中国 (CHN)：姓氏 + 2个字随机组合（如 樊 + 楚 + 东 -> 樊楚东 / 王 + 诗 + 豪 -> 王诗豪）
  CHN: {
    surnames: ["王", "林", "樊", "梁", "马", "向", "周", "徐", "袁", "陈", "黄", "温", "薛", "孙", "刘", "曹", "曾", "陶", "祝", "朱", "张", "郝", "严", "高", "牛", "全", "赛", "胡", "李", "郑", "程", "宋", "房", "孔"],
    givenChars: ["楚", "钦", "诗", "栋", "振", "东", "靖", "崑", "龙", "鹏", "启", "豪", "瑛", "彬", "励", "岑", "垣", "宇", "友", "政", "瑞", "博", "飞", "闻", "硕", "巍", "勋", "阳", "超", "帅", "玘", "松", "涛", "志", "杰", "冠", "凯", "洋", "晨", "皓", "廷", "天"]
  },
  // 日本 (JPN)：真实日本姓 + 真实日本名重组（如 松岛 + 智和 -> 松岛智和 / 户上 + 辉空 -> 户上辉空）
  JPN: {
    surnames: ["张本", "松岛", "户上", "篠塚", "宇田", "田中", "吉村", "及川", "滨田", "吉山", "萩原", "木造", "森园", "神", "英田", "水谷", "丹羽", "大岛", "松平", "吉田", "村松", "岸川", "上田", "有延", "坂井", "川上"],
    givens: ["智和", "辉空", "隼辅", "大登", "幸矢", "佑汰", "真晴", "瑞基", "一辉", "僚一", "和希", "勇人", "政崇", "巧也", "理志", "隼", "孝希", "祐哉", "健太", "雅己", "雄斗", "圣也", "仁", "大梦", "雄飞", "流星"]
  },
  // 韩国 (KOR)：真实韩国姓 + 真实韩国名重组（如 郑 + 禹珍 -> 郑禹珍 / 李 + 晙诚 -> 李晙诚）
  KOR: {
    surnames: ["李", "安", "赵", "张", "林", "吴", "朴", "姜", "金", "郑", "柳", "朱", "丁", "徐", "尹", "白", "黄"],
    givens: ["尚洙", "宰贤", "大成", "禹珍", "钟勋", "晙诚", "胜敏", "康贤", "东秀", "敏赫", "奎炫", "荣植", "承敏", "世爀", "祥恩", "东贤", "浩锡", "泽洙", "南奎", "廷佑"]
  },
  // 中国港台 (TPE / HKG)
  TPE_HKG: {
    surnames: ["林", "高", "庄", "冯", "黄", "廖", "陈", "张", "洪", "郭", "何", "姚", "关", "李", "鲍", "苏", "唐", "江"],
    givens: ["昀儒", "承睿", "智渊", "翊新", "彦诚", "振珽", "建安", "佑安", "敬恺", "冠宏", "兆恒", "钧杰", "颢桦", "钧涛", "文皓", "汉铭", "奕文", "镇廷", "天一"]
  },
  // 马来西亚 (MAS)：以马来西亚华裔常见姓氏 + 双字名组合为主（如 梁振威 / 钟子毅）
  MAS: {
    surnames: ["陈", "林", "黄", "李", "张", "王", "吴", "刘", "蔡", "杨", "郑", "谢", "梁", "钟", "曾", "许", "叶", "罗", "何", "邓"],
    givens: ["振威", "子毅", "祺燊", "俊贤", "伟强", "俊豪", "家荣", "志强", "俊杰", "健文", "俊威", "伟伦", "家豪", "俊宇", "文昌", "国伟", "耀祖", "俊瑋", "伟杰", "泽豪"]
  },
  // 泰国 (THA)：泰式前名 + 姓氏组合
  THA: {
    firstNames: ["他农", "蓬萨克", "素坤", "他威", "阿披瓦", "威拉", "帕塔拉", "颂猜", "纳塔波", "钦纳瓦"],
    lastNames: ["猜耶波恩", "素帕差", "汶纳格", "他农猜", "颂克兰", "帕塔纳", "威拉冯", "阿努颂", "占塔拉", "沙田"]
  },
  // 印度 (IND)：印度前名 + 姓氏组合
  IND: {
    firstNames: ["沙拉斯", "阿肖克", "阿尼尔", "拉胡尔", "阿米特", "维克拉姆", "阿尔琼", "萨米尔", "罗希特", "苏雷什"],
    lastNames: ["卡玛尔", "顾普塔", "沙玛", "辛格", "库马尔", "帕特尔", "梅塔", "德赛", "拉奥", "查特吉"]
  },
  // 中东/北非/土耳其 (MENA：埃及、阿尔及利亚、突尼斯、沙特、卡塔尔、伊朗、土耳其)
  MENA: {
    firstNames: ["奥马尔", "卡里姆", "优素福", "艾哈迈德", "塔里克", "哈立德", "礼萨", "阿里", "侯赛因", "埃姆雷", "穆罕默德", "布拉克"],
    lastNames: ["阿萨尔", "曼苏尔", "拉希德", "哈桑", "谢里夫", "纳赛尔", "扎德", "拉希米", "侯赛尼", "于杰尔", "德米尔", "沙欣"]
  },
  // 西非 (尼日利亚、塞内加尔)
  AFRICA_W: {
    firstNames: ["夸德里", "奥卢", "钦耶姆", "阿德", "巴巴图恩德", "马马杜", "伊斯梅拉", "阿卜杜"],
    lastNames: ["阿鲁纳", "恩迪亚耶", "迪奥普", "姆本格", "图雷", "迪亚涅", "奥孔克沃", "法耶"]
  },
  // 拉丁美洲+西班牙 (阿根廷、墨西哥、智利、古巴、巴拉圭、厄瓜多尔、波多黎各、西班牙)
  LATAM: {
    firstNames: ["迭戈", "巴勃罗", "卡洛斯", "路易斯", "费尔南多", "阿尔瓦罗", "哈维尔", "马里奥", "安德烈斯", "伊格纳西奥"],
    lastNames: ["罗伯勒斯", "冈萨雷斯", "桑切斯", "罗德里格斯", "加西亚", "马丁内斯", "洛佩兹", "埃尔南德斯", "迪亚斯", "莫拉莱斯"]
  },
  // 葡语系 (葡萄牙、巴西)
  LUSO: {
    firstNames: ["马科斯", "雨果", "布鲁诺", "里卡多", "保罗", "费利佩", "罗德里戈", "古斯塔沃"],
    lastNames: ["弗雷塔斯", "卡尔德拉诺", "席尔瓦", "桑托斯", "佩雷拉", "科斯塔", "奥利维拉", "阿劳霍"]
  },
  // 法语系 (法国、比利时)
  FRANCO: {
    firstNames: ["费利克斯", "艾利克斯", "西蒙", "雨果", "卢卡", "安托万", "马蒂厄", "皮埃尔"],
    lastNames: ["勒布伦", "高茨", "杜邦", "马丁", "贝尔纳", "罗兰", "勒鲁瓦", "菲利普"]
  },
  // 德语系 (德国、奥地利)
  GERMANIC: {
    firstNames: ["帕特里克", "蒂姆", "贝内迪克特", "马克斯", "扬", "弗洛里安", "卢卡斯", "斯特凡"],
    lastNames: ["弗朗西斯卡", "波尔", "杜达", "施密特", "穆勒", "韦伯", "克莱因", "霍夫曼"]
  },
  // 北欧 (瑞典、丹麦)
  NORDIC: {
    firstNames: ["特鲁斯", "安东", "马蒂亚斯", "约纳坦", "埃里克", "拉斯穆斯", "尼尔斯", "奥斯卡"],
    lastNames: ["莫雷加德", "卡尔伯格", "法尔克", "格罗特", "尼尔森", "安德森", "拉尔森", "彼得森"]
  },
  // 英语系 (英格兰、美国、澳大利亚、加拿大、新西兰)
  ANGLO: {
    firstNames: ["利亚姆", "卡纳克", "杰克", "瑞安", "卢克", "亚当", "康纳", "泰勒"],
    lastNames: ["皮切福德", "贾哈", "史密斯", "约翰逊", "泰勒", "威尔逊", "摩尔", "贝克"]
  },
  // 意大利
  ITALIC: {
    firstNames: ["马可", "卢卡", "安德烈亚", "亚历山德罗", "达尼埃莱", "詹卢卡"],
    lastNames: ["罗西", "里齐", "贝鲁奇", "加利", "费拉里", "布鲁诺"]
  },
  // 希腊
  HELLENIC: {
    firstNames: ["帕纳吉奥蒂斯", "乔治斯", "迪米特里斯", "扬尼斯", "尼科斯"],
    lastNames: ["吉奥尼斯", "帕帕佐普洛斯", "康斯坦丁诺", "格奥尔基乌", "瓦西利乌"]
  },
  // 中东欧/斯拉夫系 (波兰、捷克、斯洛伐克、克罗地亚、塞尔维亚、斯洛文尼亚、乌克兰、保加利亚、摩尔多瓦、科索沃、黑山、匈牙利、罗马尼亚、哈萨克斯坦)
  SLAVIC_EU: {
    firstNames: ["卢博米尔", "托米斯拉夫", "米洛什", "达科", "雅各布", "帕维尔", "马雷克", "维克多", "安杰伊", "斯拉夫科"],
    lastNames: ["约奇克", "普卡尔", "纽廷克", "雷德齐姆斯基", "诺瓦克", "科瓦奇", "波波夫", "科瓦尔斯基", "霍瓦特", "杜布罗夫斯基"]
  },
  // 兜底：暂未归类的其他国家/地区
  WESTERN: {
    firstNames: ["塞德里克", "雅各布", "保罗", "丹尼尔", "若昂", "爱德华", "安德烈", "加斯顿", "马塞洛", "基里尔"],
    lastNames: ["金克霍尔", "哈贝松", "格拉尔多", "约内斯库", "加奇纳", "阿吉雷", "格拉斯门科", "阿拉米扬", "德赛", "坦维里亚维查库尔"]
  }
};

// 国家代码 -> 姓名库分组映射（用于 generateUniqueRookieName）
// special: 使用东亚式生成规则（姓+名直接拼接，无分隔符）
// pool: 使用"名·姓"式生成规则（NAME_PARTS_DATABASE 中对应的 firstNames/lastNames）
const COUNTRY_NAME_BUCKET_MAP = {
  CHN: { kind: "special", key: "CHN" },
  JPN: { kind: "special", key: "JPN" },
  KOR: { kind: "special", key: "KOR" },
  TPE: { kind: "special", key: "TPE_HKG" },
  HKG: { kind: "special", key: "TPE_HKG" },
  MAS: { kind: "special", key: "MAS" },
  SGP: { kind: "special", key: "MAS" },
  THA: { kind: "pool", key: "THA" },
  IND: { kind: "pool", key: "IND" },
  EGY: { kind: "pool", key: "MENA" },
  ALG: { kind: "pool", key: "MENA" },
  TUN: { kind: "pool", key: "MENA" },
  KSA: { kind: "pool", key: "MENA" },
  QAT: { kind: "pool", key: "MENA" },
  IRI: { kind: "pool", key: "MENA" },
  TUR: { kind: "pool", key: "MENA" },
  NGR: { kind: "pool", key: "AFRICA_W" },
  SEN: { kind: "pool", key: "AFRICA_W" },
  ARG: { kind: "pool", key: "LATAM" },
  MEX: { kind: "pool", key: "LATAM" },
  CHI: { kind: "pool", key: "LATAM" },
  CUB: { kind: "pool", key: "LATAM" },
  PAR: { kind: "pool", key: "LATAM" },
  ECU: { kind: "pool", key: "LATAM" },
  PUR: { kind: "pool", key: "LATAM" },
  ESP: { kind: "pool", key: "LATAM" },
  POR: { kind: "pool", key: "LUSO" },
  BRA: { kind: "pool", key: "LUSO" },
  FRA: { kind: "pool", key: "FRANCO" },
  BEL: { kind: "pool", key: "FRANCO" },
  GER: { kind: "pool", key: "GERMANIC" },
  AUT: { kind: "pool", key: "GERMANIC" },
  SWE: { kind: "pool", key: "NORDIC" },
  DEN: { kind: "pool", key: "NORDIC" },
  ENG: { kind: "pool", key: "ANGLO" },
  USA: { kind: "pool", key: "ANGLO" },
  AUS: { kind: "pool", key: "ANGLO" },
  CAN: { kind: "pool", key: "ANGLO" },
  NZL: { kind: "pool", key: "ANGLO" },
  ITA: { kind: "pool", key: "ITALIC" },
  GRE: { kind: "pool", key: "HELLENIC" },
  POL: { kind: "pool", key: "SLAVIC_EU" },
  CZE: { kind: "pool", key: "SLAVIC_EU" },
  SVK: { kind: "pool", key: "SLAVIC_EU" },
  CRO: { kind: "pool", key: "SLAVIC_EU" },
  SRB: { kind: "pool", key: "SLAVIC_EU" },
  SLO: { kind: "pool", key: "SLAVIC_EU" },
  UKR: { kind: "pool", key: "SLAVIC_EU" },
  BUL: { kind: "pool", key: "SLAVIC_EU" },
  MDA: { kind: "pool", key: "SLAVIC_EU" },
  KOS: { kind: "pool", key: "SLAVIC_EU" },
  MNE: { kind: "pool", key: "SLAVIC_EU" },
  HUN: { kind: "pool", key: "SLAVIC_EU" },
  ROU: { kind: "pool", key: "SLAVIC_EU" },
  KAZ: { kind: "pool", key: "SLAVIC_EU" }
};